### ISSUE TITLE
[FEA] It would be nice if we could support Hive-style write bucketing table

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#10366]
It would be nice if we could support writing bucketing table:
```
val large = spark.range(10e6.toLong)
import org.apache.spark.sql.SaveMode
large.write
  .bucketBy(4, "id")
  .sortBy("id")
  .mode(SaveMode.Overwrite)
  .saveAsTable("bucketed_4_id")
```
driver log:
```
!Exec <DataWritingCommandExec> cannot run on GPU because not all data writing commands can be replaced
  !Output <CreateDataSourceTableAsSelectCommand> cannot run on GPU because bucketing is not supported
  *Exec <RangeExec> will run on GPU
```

**Comment by firestarman** [comment]
Spark supports [two algorithms generating the bucket id](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/V1Writes.scala#L123). We'd better support both of them.
```
if (options.getOrElse(BucketingUtils.optionForHiveCompatibleBucketWrite, "false") ==
        "true") {
        // Hive bucketed table: use `HiveHash` and bitwise-and as bucket id expression.
        // Without the extra bitwise-and operation, we can get wrong bucket id when hash value of
        // columns is negative. See Hive implementation in
        // `org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorUtils#getBucketNumber()`.
        val hashId = BitwiseAnd(HiveHash(bucketColumns), Literal(Int.MaxValue))
        val bucketIdExpression = Pmod(hashId, Literal(spec.numBuckets))

        // The bucket file name prefix is following Hive, Presto and Trino conversion, so this
        // makes sure Hive bucketed table written by Spark, can be read by other SQL engines.
        //
        // Hive: `org.apache.hadoop.hive.ql.exec.Utilities#getBucketIdFromFile()`.
        // Trino: `io.trino.plugin.hive.BackgroundHiveSplitLoader#BUCKET_PATTERNS`.
        val fileNamePrefix = (bucketId: Int) => f"$bucketId%05d_0_"
        WriterBucketSpec(bucketIdExpression, fileNamePrefix)
      } else {
        // Spark bucketed table: use `HashPartitioning.partitionIdExpression` as bucket id
        // expression, so that we can guarantee the data distribution is same between shuffle and
        // bucketed data source, which enables us to only shuffle one side when join a bucketed
        // table and a normal one.
        val bucketIdExpression = HashPartitioning(bucketColumns, spec.numBuckets)
          .partitionIdExpression
        WriterBucketSpec(bucketIdExpression, (_: Int) => "")
      }
```

**Comment by revans2** [comment]
Hash partitioning is simple because we already support it. To support the other one we would need to implement the HiveHash expression. That would be a new kernel.

https://github.com/apache/spark/blob/25d96f7bacb43a7d5a835454ecc075e40d4f3c93/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L686-L1035

Is the Spark code for this. The core hash function itself is very simple.

ints are unchanged
longs are computed as `(int) ((input >>> 32) ^ input);`
a byte array uses
```
    int result = 0;
    for (int i = 0; i < lengthInBytes; i++) {
      result = (result * 31) + (int) Platform.getByte(base, offset + i);
    }
    return result;
```
for timestamps it is
```
    val timestampInSeconds = MICROSECONDS.toSeconds(timestamp)
    val nanoSecondsPortion = (timestamp % MICROS_PER_SECOND) * NANOS_PER_MICROS

    var result = timestampInSeconds
    result <<= 30 // the nanosecond part fits in 30 bits
    result |= nanoSecondsPortion
    ((result >>> 32) ^ result).toInt
```

But for decimal numbers they convert it to a BigDecimal, normalize the value, and then call `hashCode` on it. I think in the short term we will not be able to support decimal values as the BigDecimal implementation is GPL licensed so we cannot copy it. 

The hard parts are with how some data is normalized before it is hashed.

We are also going to have problems with Maps. The way maps are hashed it depends on the order that they are stored. Maps are not ordered so we are not likely to get the same result and it might be best to just not say that we support them.

We also don't really support CalendarInterval very well, so we probably want to say at the beginning that don't support it.

Or we could just fall back to the CPU if it is a hive compatible bucketing and file a follow on for the rest.

**Comment by jlowe** [comment]
Note that the normal spark hash bucketing feature request is already tracked by #22.  We should either morph this into "I want Hive-style bucketing" and leave #22 to track normal bucketing, or make this a bucket write epic with the Hive and Spark hashing implementations as subtasks.
