### ISSUE TITLE
[FEA] Accelerate the data transfer for plan `WindowInPandasExec`

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids#1038]
**Is your feature request related to a problem? Please describe.**
No, it is an improvment.

Currently the data from cuDF will be converted to row , then to arrow before sending to the Python side. And the data coming back from the Python process will still has two conversions (arrow -> row -> cuDF).

We want to avoid the conversion between row and others.

**Describe the solution you'd like**
Convert the data from cuDF to arrow directly and vice versa.

Besides we need to replicate what the window operator does to make sure each chunk sent to Python processes is for a single partition window, and carries the window frame bounds.

**Comment by sameerz** [comment]
Hi @firestarman can you give a little more context about this feature?  Is it related to another issue or PR?

**Comment by revans2** [comment]
This is similar work that was done previously for `GpuMapInPandasExec` instead of going from CUDF to rows to arrow, can we just go directly to arrow.  The big issue with this is the processing needed on the incoming data. `GpuMapInPandasExec` just needed to divide the data up into more or less fixed size chunks. For windowing we need to replicate what the window operator does so each chunk sent to pandas is for a single partition window.

**Comment by firestarman** [comment]
Thanks Bobyy for explaining.

Hi @sameerz, I added this to track my task originally, and filed a PR for this issue just now.
Besides, i updated the description.
