### ISSUE TITLE
[QST] TPC-H q3 is slower then `gluten`

### ISSUE THREAD

**Issue by lgbo-ustc** [NVIDIA/spark-rapids#10776]
**What is your question?**

We compare `rapids` with [`gluten`](https://github.com/apache/incubator-gluten) recently. The performance of `rapids` is impressive. But we found some of the TPC-H queries are slower then `gluten`.  With q3 as an example
```sql
SELECT
    l_orderkey,
    sum(l_extendedprice * (1 - l_discount)) AS revenue,
    o_orderdate,
    o_shippriority
FROM
    customer,
    orders,
    lineitem
WHERE
    c_mktsegment = 'BUILDING'
    AND c_custkey = o_custkey
    AND l_orderkey = o_orderkey
    AND o_orderdate < date'1995-03-15'
    AND l_shipdate > date'1995-03-15'
GROUP BY
    l_orderkey,
    o_orderdate,
    o_shippriority
ORDER BY
    revenue DESC,
    o_orderdate
LIMIT 10;
```
|  | duration |  
| :--: | :--: |
| rapids | 6.167 s |   
| gluten | 3.591 s |

Is there any suggetion to improve the performance in this case ?

`rapids` is started as following
```bash
./sbin/start-thriftserver.sh \
  --master local \
  --num-executors 1 \
  --conf spark.executor.cores=1 \
  --conf spark.rapids.sql.concurrentGpuTasks=1 \
  --driver-memory 10g \
  --conf spark.eventLog.enabled=true \
  --conf spark.eventLog.dir=/workspace/test/rapids/event_logs \
  --conf spark.rapids.memory.pinnedPool.size=2G \
  --conf spark.sql.files.maxPartitionBytes=512m \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.rapids.sql.explain=ALL

```

The query visualizations in DOT format are as following
- rapids query visualization
![q3-rapids](https://github.com/NVIDIA/spark-rapids/assets/2599447/f18e6e31-4a3d-496a-a705-a07a00ddb2bc)

- gluten query visualization
![q3-gluten](https://github.com/NVIDIA/spark-rapids/assets/2599447/4bda0c6a-da01-4dbc-88fa-fe2abeb07115)

**Comment by jlowe** [comment]
Part of the issue is that the RAPIDS Accelerator run is hamstrung by only executing one task at a time (only 1 executor with only 1 core), whereas the Gluten run must be doing more in parallel.  Going through the stage task times and summing them up serially, I get around 6 seconds for all of the RAPIDS tasks, matching the wall clock time observed, yet more than 9 seconds for all the Gluten tasks which is almost 3x the observed wall clock time.  That tells me that RAPIDS is executing tasks faster than Gluten, but it's not able to run them as parallel as the Gluten setup and that makes it slower overall.

I would increase the number of executor cores to at least 2 (up to the number of cores being used by the Gluten setup) and also increase the concurrent GPU tasks to 2 (the default) unless you have a clear reason to override that (e.g.: getting a GPU OOM or seeing spills).  Depending on the size if input files and how much CPU memory is available, you may want to increase the pinned memory pool size.

**Comment by revans2** [comment]
@lgbo-ustc your data is very small. What is the scale factor that you are running at?

 * 119 MiB for customers
 * 552 MiB for orders
 * 2.09 GiB for lineitem

What hardware are you running on? Just curious about your decision to set the memory limits and concurrency that you did.

GPU processing tends to scale sub-linearly. Doubling the data, up until the GPU is fully utilized, tends to not double the run time. So tuning at this point is likely to be in the details.

  * Gluten/Velox Stage 13 (80 ms) is the same as RAPIDs stage 24 (64 ms) - this is so small we can ignore it for now.
  * Gluten/Velox Stage 12 (1560 ms) is the same as RAPIDS stage 25 (229ms + 554ms = 783 ms) Even with a concurrent value of 1 RAPIDS is 2x faster than gluten. If we could set the concurrency to 2, it would likely be faster, or if we tuned the max partition bytes we might get it all in a single task with a single batch.
  * RAPIDS stage 28 is due to AQE starting out doing a shuffled join and then switching to a broadcast join. It looks like gluten was not run with AQE.
  * Gluten/Velox stage 15 (274 ms MAX) is the same as RAPIDS stage 30 (140 ms + 317 ms = 457 ms) Again concurrency is playing a role here. If you could increase the concurrency if might help.
  * Gluten/Velox stage 14 (2542 ms MAX) is the same as RAPIDS stage 26 (490 ms AVG * 7 tasks =  3,430 ms) Here RAPIDS had 7 tasks, but gluten only had 3. If we could set the max partition bytes a little larger, and the batch size larger too it would likely speed things up a lot.
  * The last stage is hard to tell because TakeOrderedAndProjectExecTransformer made it so that most of the processing time for that stage is lost. It plays some games internally with a shuffle that is not counted which can cause this.

In general if you have the hardware to do it I would suggest you follow our tuning guide.

Have a concurrency of at least 2.
Have CPU cores that are probably about 2+ the concurrency, so we can overlap I/O and computation.
Set max partition bytes larger

**Comment by lgbo-ustc** [comment]
Thanks very much. We also found that there is not enough concurrency to process the tasks by timeline. After making it the same as `gluten`, the end to end duration is abount 1.3s now.

**Comment by jlowe** [comment]
Thanks for the update!  Looks like things are running properly now.
