### ISSUE TITLE
[QST] GPU Memory is completely consumed in AWS-EMR 

### ISSUE THREAD

**Issue by akmalmasud96** [NVIDIA/spark-rapids#10827]
I am trying to run Spark-Rapids with AWS-EMR. I am facing a problem that the GPU memory is completely consumed when the processing is initiated. And there is no space left in the GPU memory to perform processing.
Attached is an image, showing this phenomenon. 

The AWS-EMR version is 7.1.0. 
I want to ask that how can I solve this problem ?

![image](https://github.com/NVIDIA/spark-rapids/assets/26347692/ef92ef69-011d-4df3-aed2-ab9a208b2a78)

**Comment by akmalmasud96** [comment]
The issue was due to configuring the following parameter 
"spark.plugins":"com.nvidia.spark.SQLPlugin"
Removing it, resolved the issue.

**Comment by abellina** [comment]
@akmalmasud96 just making sure I understand, do you want to run the the spark-rapids plugin? If so the spark.plugins flag is required. Thanks!

**Comment by jlowe** [comment]
The RAPIDS Accelerator consumes almost all of the GPU memory by default.  It does not expect to share the GPU with another process.  You can configure the RAPIDS Accelerator to consume much less GPU memory, although that often has detrimental effects on performance due to extra spilling to fit within the smaller amount of GPU memory.  See the [`spark.rapids.memory.gpu.maxAllocFraction`](https://github.com/NVIDIA/spark-rapids/blob/main/docs/configs.md#memory.gpu.maxAllocFraction) or [`spark.rapids.memory.gpu.reserve`](https://github.com/NVIDIA/spark-rapids/blob/main/docs/additional-functionality/advanced_configs.md#memory.gpu.reserve) configs to limit the amount of memory used, either by setting a maximum fraction or the amount of memory to leave reserved, respectively.

**Comment by akmalmasud96** [comment]
Thanks for describing. I had figured it out. I want to ask that can we use Raft in spark-rapids for vector operations ?
