### ISSUE TITLE
[BUG] GPU degreees function does not overflow

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids#109]
**Describe the bug**
On very large numbers GpuToDegrees will not overflow and produce inf when the GPU version does.  This appears to be an order of operations issues where the CPU version multiplies by 180 and then divides by pi, while we for performance reasons multiply by (108/pi).  It should be a minor fix to make this work.

A python test is being added to reproduce this issue.

**Comment by thirtiseven** [comment]
The toDegrees in spark is a direct call to the toDegrees in the java math library, but since JDK 9 the java [implementation](http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/47558493c9c0) has changed to the same order of calculation as the current plugin (from angrad * 180.0 / PI to angrad * (180.0 / PI)), So the results of spark will differ depending on the JDK version in the runtime environment.

Do we need to add support for higher versions of the JDK to ToDegrees to match spark's output? It can perhaps be implemented by determining the Java version when executing the function.  

Some tests: current code is XFAIL on JDK8 and XPASS on JDK11, and following code in this [PR](https://github.com/NVIDIA/spark-rapids/pull/5996) is PASS on JDK8 and FAIL on JDK11 for case test_degrees.  
```Scala
case class GpuToDegrees(child: Expression) extends GpuUnaryMathExpression("DEGREES") {

  override def doColumnar(input: GpuColumnVector): ColumnVector = {
    val tmp = withResource(Scalar.fromDouble(180d)) { multiplier =>
      input.getBase.mul(multiplier)
    }
    withResource(tmp) { _ =>
      withResource(Scalar.fromDouble(Math.PI)) { pi =>
        tmp.div(pi)
      }
    }
  }
}
```

**Comment by revans2** [comment]
If the JDK itself decided that our implementation is better, then I am inclined to just keep the current one and add docs explaining the difference. Then we can have tests for an exact answer that are skipped if the JDK version is JDK 8 or below.

@sameerz do you have any objection to this?
