### ISSUE TITLE
[BUG] `input_file_name()` returns empty result.

### ISSUE THREAD

**Issue by liurenjie1024** [NVIDIA/spark-rapids#10973]
**Describe the bug**
`input_file_name()` method returns empty result.

**Steps/Code to reproduce bug**
```sql
spark-sql (default)> drop view t1
                   > ;
Time taken: 0.414 seconds
spark-sql (default)> create view t1 as select input_file_name() as fin, * from parquet.`/home/rayliu/Downloads/test/spark-warehouse/dst_table/a=0/part-00000-a2c59f79-5a6a-4652-ada3-2d2e79c2cbe3.c000.snappy.parquet`;
Time taken: 0.187 seconds
spark-sql (default)> drop view t2;
Time taken: 0.139 seconds
spark-sql (default)> create view t2 as select input_file_name() as fin, * from parquet.`/home/rayliu/Downloads/test/spark-warehouse/dst_table/a=0/part-00191-e586e5b8-a6e5-4900-87b3-9766abb22b4c.c000.snappy.parquet`;
Time taken: 0.086 seconds
spark-sql (default)> select t1.fin as f1, t2.fin as f2 from t1 inner join t2;
```

**Expected behavior**
It should returns filenames of both files.

**Environment details (please complete the following information)**
 We can reproduce it in spark shell when enable spark rapids plugin.

**Additional context**
No.

**Comment by jihoonson** [comment]
Hi @liurenjie1024, thank you for the report. I'm afraid, though, that I could not reproduce the issue on my side. Here are the steps I took to reproduce it:

```
scala> spark.sql("create view t1 as select input_file_name() as fin, * from parquet.`/my/parquet/file1.parquet`").show
...
scala> spark.sql("create view t2 as select input_file_name() as fin, * from parquet.`/my/parquet/file2.parquet`").show
...
scala> sql("select t1.fin as f1, t2.fin as f2 from t1 inner join t2").show
+--------------------+--------------------+
|                  f1|                  f2|
+--------------------+--------------------+
|file:///my/parq...|file:///my/parq...|
+--------------------+--------------------+
```

As you see above, the same join query returned a row of two columns of the file paths. So, I would like to ask you these:

- What version of spark and spark-rapids plugin did you use for your testing? If you used an old version, could you try the latest version and see if the issue is still there?
- Could you make sure that your query runs on GPU? You can do it by running an explain query, i.e., `explain select t1.fin as f1, t2.fin as f2 from t1 inner join t2`. The operators in the query plan returned by the explain should be prefixed by `Gpu` as seen below.
  - If the query plan contains CPU operators instead, you could set `spark.rapids.sql.explain` to `NOT_ON_GPU` to debug it.
  - In my case, the query was running on CPU with `spark.sql.adaptive.enabled=true`. You may want to disable the adaptive execution if you see the same issue.

```
== Physical Plan ==
GpuColumnarToRow false
+- GpuProject [fin#452 AS f1#450, fin#457 AS f2#451]
   +- GpuBroadcastNestedLoopJoin Inner, GpuBuildRight, [fin#457], 1073741824
      :- GpuProject [input_file_name() AS fin#452]
      :  +- GpuFileGpuScan parquet [] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/my/parquet/file1.parquet, PartitionFilters: [], PushedFilters: [], ReadSchema: struct<>
      +- GpuBroadcastExchange IdentityBroadcastMode, [plan_id=1358]
         +- GpuProject [input_file_name() AS fin#457]
            +- GpuFileGpuScan parquet [] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex[file:/my/parquet/file2.parquet, PartitionFilters: [], PushedFilters: [], ReadSchema: struct<>
```

**Comment by jihoonson** [comment]
@liurenjie1024 that's great! Do you know which PR/commit fixed this issue?

**Comment by jihoonson** [comment]
@liurenjie1024 I see. Thanks for testing!
