### ISSUE TITLE
Address remaining review issues from #11197

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#11208]
UPDATE https://github.com/NVIDIA/spark-rapids/issues/11208#issuecomment-2261696363

ORIGINAL

**Is your feature request related to a problem? Please describe.**
When access unshimed classes from shimed classes, some customer Env will report class not found error, while premerge now can not reproduce.
Gera proposed a method to report error, refer to https://github.com/NVIDIA/spark-rapids/pull/11197#issuecomment-2231580947

**Describe the solution you'd like**
- First access unshimed classes from shimed classes. 
  e.g.: 
     In a GpuxxxExec, access `GpuColumnVectorUtils`
- Use this method to reproduce: refer to https://github.com/NVIDIA/spark-rapids/pull/11197#issuecomment-2231580947
- Write a simple case.

**Comment by jlowe** [comment]
Would prefer to see this addressed by removing the explicit list of unshimmed classes and instead move all unshimmed classes to sql-plugin-api.  Advantage of that approach is the compiler will catch this at build time.  See #6565

**Comment by gerashegalov** [comment]
I think it will be sufficient to limit the scope of this issue to addressing the review comments #11197 
-  GpuColumnVectorUtils should move to sql-plugin-api (and inspect if there are more classes from the ushimmed list that can move without much refactoring)
- Since many of such failures are caught only in shuffle_test, see if we can introduce some mechanism that runs a random selection of tests as shuffle tests even if they are not labeled as such specifically
