### ISSUE TITLE
[FEA] explode() can take expressions that generate arrays

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#1125]
**Is your feature request related to a problem? Please describe.**
This feature comes from the example in https://github.com/NVIDIA/spark-rapids/issues/1079. 

```
    val myudf: (String) => Array[String] = a => {
      a.split(",")
    }
    val u = makeUdf(myudf)
    val dataset = List("first,second").toDF("x").repartition(1)
    var result = dataset.withColumn("new", explode(u(col("x"))))
    result.explain(true)
```
explode() should be able to deal with "created arrays" but current explain shows:
```
    *Exec <ProjectExec> could run on GPU
      !Exec <GenerateExec> cannot run on GPU because Only posexplode of a created array is currently supported
```

**Additional context**
This feature needs the fix for https://github.com/NVIDIA/spark-rapids/issues/1079 first.

**Comment by revans2** [comment]
Out explode and pos_explode implementation is lacking right now.  This is due to limitations in cudf.

https://github.com/rapidsai/cudf/issues/2975 and https://github.com/rapidsai/cudf/issues/6151 are what we need to be able to start to tackle this.  We might be able to hack something together sooner if the time frame is tight, but that I am even a little skeptical of because we don't have a length for lists implementation yet.

**Comment by GaryShen2008** [comment]
@wjxiz1992 Could you help to verify it on 0.6 since https://github.com/NVIDIA/spark-rapids/pull/2215 has been merged?

**Comment by wjxiz1992** [comment]
fixed:

```
+- GpuGenerate gpuexplode(split(x#5, ,, -1)), [x#5], false, [new#8]
   +- GpuShuffleCoalesce 2147483647
```
