### ISSUE TITLE
[QST] Where is AccessibleArrowColumnVector initiated, it seems like it can be removed

### ISSUE THREAD

**Issue by rluvaton** [NVIDIA/spark-rapids#11862]
**What is your question?**
Where is `AccessibleArrowColumnVector` initiated, I don't see anywhere that it's actually being used

**Comment by tgravescs** [comment]
the AccessibleArrowColumnVector API was originally added to allow users to more easily write a custom DatatSource V2 datasource  to read Arrow Data and have the Spark Rapids plugin optimize the copy of the data to the GPU.  So you would have to write your own DataSource V2 and use that class for it to be used.

Now having said that, no one is actively using it and it looks like it is actually no longer accessible due to the way we shim our jar because its not globally accessible anymore. 

Were you trying to use this class?  

I will file an issue to just remove this class.

**Comment by rluvaton** [comment]
Not trying just reading the code trying to understand
