### ISSUE TITLE
[BUG] Parquet Output File Sizes Unbalanced Compared to CPU Implementation

### ISSUE THREAD

**Issue by btong04** [NVIDIA/spark-rapids#1502]
**Describe the bug**
Parquet files written by GPU cluster are different than those written by CPU cluster. 

**Steps/Code to reproduce bug**
Load parquet file directory with balanced data (same number of rows, columns, and row groups). Write data to disk immediately and check file size.
```
import os
import shutil

data_dir = '/FileStore/tables/telco_dat_small/parquet'
df = spark.read.parquet(data_dir)

num_files = len(os.listdir('/dbfs'+data_dir)) # Number of input files

# Write data to dbfs or other network storage location. 
etl_output_dir = '/tmp/bt/test_output'

# WARNING: ENTIRE etl_output_dir WILL BE DELETED
# Remove directory if exists:
if os.path.exists('/dbfs'+etl_output_dir):
    shutil.rmtree('/dbfs'+etl_output_dir)

df.write.parquet(etl_output_dir)
```

```
%sh
ls -all /dbfs/tmp/bt/test_output
```

**Expected behavior**
Exported files should be the same in both implementations using default settings. For example, 5 parquet files with similar size are read into spark. CPU cluster wrote out 5 files with similar size, but GPU cluster wrote out 21 files of varying sizes. Applying .coalesce() can reduce the number of files with minimal performance impact, but the data remains unbalanced. It is desirable that each output file contains the corresponding rows from it's source input file. 

**Environment details (please complete the following information)**
 - Environment location: Databricks 7.3 LTS ML on 2 worker cluster with either i3.4xlarge (CPU) or g4dn.4xlarge (GPU). Running spark-rapids 0.3 release.
 - Spark configuration settings related to the issue:
Default configuration for CPU cluster.
GPU cluster has the following options applied: 
spark.task.resource.gpu.amount 0.0625
spark.plugins com.nvidia.spark.SQLPlugin
spark.locality.wait 0s
spark.rapids.memory.pinnedPool.size 2G
spark.sql.adaptive.enabled false
spark.databricks.delta.optimizeWrite.enabled false
spark.rapids.sql.concurrentGpuTasks 2

**Additional context**
Data is part of an ETL and feature engineering pipeline where it is being staged and exported to disk for subsequent consumption in an ML pipeline. Having output data that corresponds to the input file is desirable for record keeping, especially when we are only augmenting the data with more columns and exporting the results to disk. Maybe the issue is related to the input file having row groups within each file?

**Comment by tgravescs** [comment]
that is weird, can you confirm the number of tasks that ran during the write stage between CPU and GPU?  Did GPU have 5 tasks at the end but wrote 21 files?

**Comment by tgravescs** [comment]
Also can you tell me the size of the 5 files read?

**Comment by btong04** [comment]
There were 24 tasks in the GPU cluster and 5 tasks on the CPU cluster in the main job. The input files were each 17.1MB on disk.

**Comment by tgravescs** [comment]
Yeah so in this case spark uses the default parallelism because there are no other shuffles.  I ran this on normal Apache Spark on the CPU and it does the same thing. Databricks must have some additional logic in it to reduce the number.   You can see this if you edit the gpu cluster config and add this: spark.default.parallelism 7, then you will get 7 files.
if you run any other queries that would do a shuffle - join, groupby, etc, then this wouldn't be an issue as it would use other configs.

if this a real use case where someone is just trying to change formats or something?

**Comment by btong04** [comment]
The example code provided is a toy model to show the unexpected behavior. The actual use case is: (1) read in flat file with class balanced categorical data; (2) perform feature engineering, data augmentation, encoding, etc. to add more columns; (3) output updated data that aligns with input to avoid unnecessary shuffling. The input data is balanced in terms of data distributions and it is desirable to keep it that way.

**Comment by tgravescs** [comment]
note that here we use the same logic Apache Spark does for the max split size: https://github.com/apache/spark/blob/branch-3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FilePartition.scala#L86

in this case you have 32 cores but you only get 24 tasks, this is because the open cost in bytes ends up being the limit.
this is not a bug as we do the same as Apache Spark, if we wanted to try to do something smarter similar to Databricks that would be a feature request.
