### ISSUE TITLE
[FEA] Test redefined window operation

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#1519]
**Is your feature request related to a problem? Please describe.**
This stems from https://github.com/apache/spark/commit/e43255051c where Spark now will not give an output but throw a parse exception when windows are redefined.
**Describe the solution you'd like**
Make sure we match CPU behavior

**Comment by revans2** [comment]
This change was completely in Sparks SQL parser. I personally don't see a lot of value in writing a test for code that is not in our project. We mostly just need to make sure that we avoid doing this in any tests going forward. I know we are not doing it in any current tests because the tests are not failing in this way on spark 3.1
