### ISSUE TITLE
[BUG] Incorrect output from partial-only hash aggregates with multiple distincts and non-distinct functions

### ISSUE THREAD

**Issue by kuhushukla** [NVIDIA/spark-rapids#153]
**Describe the bug**
For hash aggregates with only partials on the gpu and that contain `gpufirst` can yield wrong results. 
We know that gpu first can be incompatible with cpu first operator but we need to either fall back somehow to the cpu in this case post detection or fix the gpu plan to yield correct results.

**Steps/Code to reproduce bug**
```
@ignore_order
@allow_non_gpu(
    'HashAggregateExec', 'AggregateExpression',
    'AttributeReference', 'Alias', 'Sum', 'Count', 'Max', 'Min', 'Average', 'Cast',
    'KnownFloatingPointNormalized', 'NormalizeNaNAndZero', 'GreaterThan', 'Literal', 'If',
    'EqualTo', 'First', 'SortAggregateExec', 'Coalesce')
@pytest.mark.parametrize('data_gen', get_struct_gens(
    marked_params=params_markers_for_avg_sum), ids=idfn)
def test_hash_multiple_mode_query_fail(data_gen):
    print_params(data_gen)
    assert_gpu_and_cpu_are_equal_collect(
        lambda spark: debug_df(debug_df(gen_df(spark, data_gen, length=3))
            .groupby('a')
            .agg(f.count('a'),
                 f.countDistinct('b'),
                 f.countDistinct('c')
                )), conf=_no_nans_float_conf_partial)
```

**Expected behavior**
Cpu count = 1, Gpu count =0.
CPU Full output : 
```
[Row(a=-2697073954890740236, count(a)=1, count(b)=1, count(c)=1), Row(a=-431710025170174585, count(a)=1, count(b)=1, count(c)=1), Row(a=7198729688045931692, count(a)=1, count(b)=1, count(c)=0)]
```
GPU Full output : 
```
[Row(a=-2697073954890740236, count(a)=0, count(b)=1, count(c)=1), Row(a=-431710025170174585, count(a)=1, count(b)=1, count(c)=1), Row(a=7198729688045931692, count(a)=1, count(b)=1, count(c)=0)]
```

**Comment by nartal1** [comment]
Spark changes the plan if there are multiple distincts and non distinct functions in partial only hash aggregates. It computes non distinct using `First` operator. Since gpu_first is not deterministic, the result will be incorrect if all the rows required for non distinct functions are not in the first batch being sent to CPU.  If there is only one partition, then we get the correct result. For multiple partitions, when GPU sends result of the first batch, CPU would consider the non distinct function's `First` as the final result(which is incorrect). 
Thanks to @kuhushukla in helping to understand GpuHashAggregates. We don't see any other way around than falling back to CPU. Will create a PR for falling back to CPU for this  case.
