### ISSUE TITLE
[FEA] Support ScalarSubquery

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#1600]
**Is your feature request related to a problem? Please describe.**
`ScalarSubquery`, which turning the output of a (sub)query into a single scalar value, has yet supported under GPU. This feature is important for better performance.

**Describe the solution you'd like**
Implement GPU overrides for `org.apack.spark.sql.execution.SubqueryExec` and `org.apack.spark.sql.execution.ScalarSubquery`.

**Comment by revans2** [comment]
I am not sure we need to implement `SubqueyExec` for this use case.  `ScalarSubquery` will run a query that produces a single result. One row of one column. It will run that sub-query and collect the result back to the driver.

https://github.com/apache/spark/blob/5718d64f3104f7a24a9d4b619748bcca03031c48/sql/core/src/main/scala/org/apache/spark/sql/execution/subquery.scala#L82-L96

But then it keeps the data cached in the expression and just returns that value as if it were a literal.

There is really almost no value at all in trying to make the various `SubqueryExecBase` implementations run on the GPU because it is returning just a single value.  If it was more data then it might make since to do something like BroadcastExchangeExec so we can keep a large amount of the data columnar.  Here the amount of data is likely small enough that there is no point.
