### ISSUE TITLE
[BUG] `upper` expression documentation is out of date

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#1672]
The documentation describing the reasons why `upper` is not supported on the GPU by default is out of date.  It claims that the plugin cannot handle cases where characters change byte widths during the operation and points to a cudf issue which has been resolved.

We're still missing some corner-case characters, depending upon the Unicode standard the JVM is targeting, but I believe we're now covering most of the cases where the byte width changes.  The docs should be updated to point to either a new cudf/plugin github issue tracking what's left to do or other documentation that describes the cases that are currently not handled.

**Comment by sameerz** [comment]
Once we document this, we may want to consider having `upper` back on the GPU by default.

**Comment by sameerz** [comment]
Since we've set `spark.rapids.sql.incompatibleOps.enabled=true`, I'd like to continue to chip away at configs users need to set on their own.   @andygrove are you familiar with the remaining `upper`, `lower` and `initcap` corner cases?  I am wondering if we just need to document those, or if there is additional work pending to enable these operations.  

Also, our documentation seems to imply that setting incompatibleOps to true will enable even `upper`, `lower` and `initcap` to be true.  I am not sure if that is the case or not.  If not, we should clarify the docs. 

From the [docs](https://nvidia.github.io/spark-rapids/docs/configs.html#supported-gpu-operators-and-fine-tuning) : 

> NOTE: Setting [spark.rapids.sql.incompatibleOps.enabled=true](https://nvidia.github.io/spark-rapids/docs/configs.html#sql.incompatibleOps.enabled) will enable all the settings in the table below which are not enabled by default due to incompatibilities.
