### ISSUE TITLE
GPU support for UDF

### ISSUE THREAD

**Issue by atam003** [NVIDIA/spark-rapids#1762]
**Is your feature request related to a problem? Please describe.**
Currently, we do define a few UDF for our spark applications. but those UDF fails to run on GPU.
For example - INSTR, TO_DATE, CONCAT, IN etc.

**Describe the solution you'd like**
GPU support for such UDF.

**Describe alternatives you've considered**
NA

**Additional context**
Posting on behalf of Informatica.

**Comment by jlowe** [comment]
Thanks for the report, @atam003.  Unfortunately this issue is too broad and vague to be actionable.  The RAPIDS Accelerator will not be able to automatically translate arbitrary UDFs to GPU code anytime soon, if ever.  However we do have a few ways that UDFs can be handled which may or may not be helpful for your use cases.

There is a [UDF compiler](https://github.com/NVIDIA/spark-rapids/tree/main/udf-compiler) that can automatically translate some simple UDFs into equivalent Spark Catalyst operations which are then translated to the GPU like other Catalyst operations found in Spark query plans.  The compiler is experimental and therefore disabled by default, but you could try it if you're interested and think it could help for your UDF cases.

Another option would be to update the code for the UDFs to supply GPU versions of them.  This of course requires coding on the user's part and therefore is not an automatic option, but it has the advantage of being able to supply optimized GPU code for the UDF.  See the [RAPIDS Accelerated UDF documentation](https://github.com/NVIDIA/spark-rapids/blob/branch-0.4/docs/additional-functionality/rapids-udfs.md) for details.  Support for RAPIDS Accelerated UDFs is available in the 0.4 version of the accelerator which we are [planning on releasing in the next few weeks](https://github.com/NVIDIA/spark-rapids/issues/1666).

It may be more fruitful to take a few, key UDFs that you are interested in supporting on the GPU and file separate issues for each one, detailing in each issue what that particular UDF does.  We can then decide for each one what the best approach may be.
