### ISSUE TITLE
[FEA] Integration test jar should include scallop dependency

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#1801]
**Is your feature request related to a problem? Please describe.**
The benchmark utilities in the integration test jar depend on scallop when run as a spark application via spark-submit but we do not include the scallop dependency in the jar. We should either include it or add documentation explaining how to download this jar and add to the classpath in Spark.

**Comment by revans2** [comment]
I think we already build one.  You just have to pick the right jar.

`rapids-4-spark-integration-tests_2.12-0.5.0-SNAPSHOT-jar-with-dependencies.jar` instead of `rapids-4-spark-integration-tests_2.12-0.5.0-SNAPSHOT.jar`

```
$ jar -tvf integration_tests/target/rapids-4-spark-integration-tests_2.12-0.5.0-SNAPSHOT-jar-with-dependencies.jar | grep scallop | head -1
     0 Wed Aug 19 14:49:18 CDT 2020 org/rogach/scallop/
```

If you want the default jar to have it in there, then we need to update the configuration for the maven-assembly-plugin in the pom.xml, and because we would end up distributing someone else's code we probably need to update NOTICE-binary as well to indicate the copyright of scallop and anything else we pull into that jar.

**Comment by andygrove** [comment]
Thanks @revans2 I didn't realize that the separate jar with dependencies was already available
