### ISSUE TITLE
[FEA] support GpuLiteral of ArrayType

### ISSUE THREAD

**Issue by sperlingxx** [NVIDIA/spark-rapids#1902]
**Is your feature request related to a problem? Please describe.**
Currently, `GpuLiteral` doesn't support nested types (Array, Struct, Map). Because underlying cuDF.Scalar doesn't support nested rapids types. Meanwhile, GpuLiteral of ArrayType is the essential feature for `GpuExplode` and other GpuExpressions. For now, we have a substituted implementation, which provide partial support of  GpuLiteral on ArrayData. We should replace the temporary solution once cuDF support Scalar on ListType.

**Comment by revans2** [comment]
https://github.com/rapidsai/cudf/pull/7584 is adding in support for list scalars, and it looks like it will support full nesting of types because it takes a column_view as the data passed in.  We will need to make java APIs for it and also verify that it will work to create a ColumnVector from a scalar value.
