### ISSUE TITLE
[BUG] Could not allocate native memory when running DLRM ETL with --output_ordering input on A100

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids#1953]
**Describe the bug**
When running DLRM ETL with --output_ordering input on A100, some tasks failed by "Could not allocate native memory"
The job finally succeeded running but there always were some failed tasks. 

It can't reproduce on DGX-2 V100. 
And it can't reproduce after removing --output_ordering input.

**Steps/Code to reproduce bug**
git clone https://gitlab-master.nvidia.com/dl/JoC/dlrm_pyt
git checkout updating-for-20.11-release
docker build -t nvidia_dlrm_preprocessing -f Dockerfile_preprocessing --build-arg DGX_VERSION=DGX-A100 .
docker run --runtime=nvidia -it --rm --ipc=host -v /raid/dlrm_data:/data nvidia_dlrm_preprocessing bash
cd /workspace/dlrm/preproc
./prepare_dataset.sh 2 GPU Spark

Version:
cudf-0.18.1-cuda11.jar
rapids-4-spark-2.12-0.4.0-rc

**Expected behavior**
No failed task.

**Environment details (please complete the following information)**
 - Environment location: Standalone
 - Spark configuration settings related to the issue: refer to the script.
 

**Additional context**

**Comment by jlowe** [comment]
Can you elaborate on the two environments?  DGX2 machines can potentially have a lot of GPU instances and total GPU memory, (e.g.: 16 GPUs with 32GB each).  How many executors were used and how much total GPU memory was available in each environment?

**Comment by GaryShen2008** [comment]
DGX-2 has 16 GPUs(32GB each), A100 has 8 GPUs(40GB each).
The main problem is that, the OOM issue occured when transforming half of day_23 data, which was about 20GB.

**Comment by GaryShen2008** [comment]
As I tested on A100 & V100 again, the issue was reproduced only when setting spark.sql.autoBroadcastJoinThreshold=1GB.
After reducing it to 512MB, the issue was gone.

Furthermore, why it can be reproduced on A100 not V100, is that we set to use more CPU cores per executor.
on A100, we used 32 cpu cores per executor, it reproduced.
After I reduced to 10 cpu cores per executor, the problem was gone.
Whatever I set the spark.task.cpus=32 or 1, the problem happened when 32 cpu cores per executor.

I'm trying to understand the reason.

**Comment by revans2** [comment]
> As I tested on A100 & V100 again, the issue was reproduced only when setting spark.sql.autoBroadcastJoinThreshold=1GB.
> After reducing it to 512MB, the issue was gone.
> 
> Furthermore, why it can be reproduced on A100 not V100, is that we set to use more CPU cores per executor.
> on A100, we used 32 cpu cores per executor, it reproduced.
> After I reduced to 10 cpu cores per executor, the problem was gone.
> Whatever I set the spark.task.cpus=32 or 1, the problem happened when 32 cpu cores per executor.
> 
> I'm trying to understand the reason.

I think the reason is with how we deal with broadcast joins. Broadcast variables are singletons. In 0.3 we had to do a work around to a performance issue in cudf where nulls were not handled properly. We removed this early in on 0.4, but had to partially revert it for some types of joins which were missed in the cudf fix.  This resulted in us making a copy of the broadcast data, to filter out the nulls, ahead of time.  We thought we could get around this by having the changed data be a singleton for the instance of the join class, but because of java serialization it turned out that it was one copy per task thread, instead of one copy per executor.

So the more tasks you have the more threads there are and the more copies of the broadcast data end up on the GPU. It is a lot better in 0.4 than it was in 0.3, but it is still not perfect.

**Comment by GaryShen2008** [comment]
Thanks, Bobby. 
It can explain some of the symptom.

Why the issue still happened when I set spark.task.cpus=32? 
It should make the job only create one task per executor at the same time.
It surprised me that it can be reproduced when using executor-cores=32, spark.task.cpus=32, but can't when executor-cores=10, cpus=10(as same as DGX-2 v100).

**Comment by revans2** [comment]
Because of how spark/scala interact with java serialization.  In the join code the build table is a lazy val

https://github.com/NVIDIA/spark-rapids/blob/cd6bd8e21ea27cf7d401598abaccf12d3813b327/shims/spark300/src/main/scala/com/nvidia/spark/rapids/shims/spark300/GpuBroadcastHashJoinExec.scala#L142-L154

I made the assumption that the lazy val would truly be a singleton per executor process but that is wrong. The lazy val ends up being one per thread, because of how spark de-serializes the code for the execution.  Typically spark has a single thread in a pool per task in the executor.  So now the more tasks you have in the executor the more copies of that lazy val you get.

That said we should dig in deeper to see exactly what is happening with the broadcast data, because the underlying data should still be a singleton for the most part.  The table should just be pointing at the same columns and incrementing their reference counts, unless there is something besides just column references in the join keys.

**Comment by sameerz** [comment]
Might depend on https://github.com/rapidsai/cudf/issues/7300 so that the null filtering workaround can be removed.  Ideally need to do a memory dump on the plugin heap and understand why we are OOM'ing.

**Comment by GaryShen2008** [comment]
I'd like mark it as P2 because I found the issue only happened when giving more CPU cores on A100 than on V100.
Need to learn how to dump the RMM pool memory to figure out what happened.

**Comment by sameerz** [comment]
Marking for 0.6 as there is a plan to work on the dependent cudf issue in the 0.20 timeframe.

**Comment by sameerz** [comment]
@GaryShen2008 the dependent issue was resolved, can you try testing again?

**Comment by GaryShen2008** [comment]
> 
> 
> @GaryShen2008 the dependent issue was resolved, can you try testing again?

Yes, it works with the latest v21.06.0-snapshot.
So, is it related to https://github.com/NVIDIA/spark-rapids/pull/2502?

**Comment by GaryShen2008** [comment]
I have verified it by using the latest nightly snapshot jar.
Close it.
