### ISSUE TITLE
[FEA] Improve handling of shuffles during integration tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#2146]
**Is your feature request related to a problem? Please describe.**
While working on #2145 I noticed that the existing repartition test was not actually testing anything on the GPU.  The test was supposed to be testing that a partition and shuffle matched the CPU, but the plan optimized out the GPU shuffle since the other parts of the plan were not columnar.  The test should have failed since the plan was not columnar in any way, but it went ahead and compared CPU to CPU which isn't helpful.

**Describe the solution you'd like**
There should be a mechanism to avoid ignoring shuffles that are not on the GPU or force shuffles to be translated to the GPU during planning.

**Comment by sameerz** [comment]
When doing the review of tests that have this problem, focus on tests that are shuffle related.

**Comment by revans2** [comment]
I was asked in standup how many tests are failing when we add back in the check for the exchange to be on the GPU for all of the tests.

It turns out that we have 8 scala tests that fail, and 209 python tests.  The 209 number is a bit misleading because we have parametrized most of the tests there for types so it is actually a much smaller number of specific tests that are failing in this way.

I'll take a crack at fixing fixing the tests, but I may have to take a closer look at the python tests because I would not expect them to have a shuffle on the CPU normally.
