### ISSUE TITLE
[BUG] Spark Pickle produces incorrect key labels for GenericRowWithSchema 

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#2329]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids/pull/2169 worked around https://issues.apache.org/jira/browse/SPARK-35108

We need to retest since this is supposed to be fixed with https://issues.apache.org/jira/browse/SPARK-34545  and put a test case back in for the fixed spark versions.

**Comment by revans2** [comment]
I'm not sure we need a test case for this. It is a Spark bug not a bug in the Rapids Accelerator. The issue was exposed completely by accident because I happened to pick a test that caused the issue.  The work around was to modify the test to still be 100% valid for what we are testing in RAPIDS, but not expose the bug in Spark. In fact the new test has more coverage, not less. So if we add in a test we would have to make it conditional on Spark 3.0.3 and above, 3.1.2 and above and 3.2.0 and above. I personally don't think it is worth it.

**Comment by revans2** [comment]
I did manually verify the fix in Spark too.
