### ISSUE TITLE
[FEA] Use cuFile to write PCBS cache

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#2464]
Look into if we can leverage cuFile to write parquet file directly to GPU memory 

https://github.com/rapidsai/cudf/pull/7444

**Comment by revans2** [comment]
cuFile writes to a NVMe, not into GPU Memory.  The current APIs that we have already can write directly into GPU memory. We copy the data out to host memory because that is what Spark wants so it can serialize the data out to disk if it feels like it or keep it cached in host memory. Where it is cached is controlled by the user.
