### ISSUE TITLE
[BUG] Too few executors being launched in YARN cluster

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#2847]
**Describe the bug**
Discrepancy in the number of executors submitted via Livy and logged in Spark History server under Environment tab, vs the number of executors actually being spun up.

**Steps/Code to reproduce bug**
I have a 3 node YARN cluster with the following configuration:

Node size: 16 cores, 110 GB RAM, 1 GPU
Number of nodes: 3
I am trying to spin up the following Spark session on this cluster:

Driver cores: 4
Driver memory: 5g
Executor cores: 4
Executor memory: 5g
Number of Executors: 6

I can also see the above being set accordingly in the Environment tab on Spark history server, however only 3 executors actually get created. Is this because Spark RAPIDS supports only 1-1 mapping between executor and GPUs? How is this enforced on the Spark side?

**Expected behavior**
Understand the expectation of number of executors that will spin up for a Spark RAPIDS enabled application.

**Environment details**
 - Environment location: YARN
 - Spark configuration settings related to the issue: Mentioned above

**Additional context**
The job with above config succeeds, I am mostly looking to understand the executor discrepancy. 
When running similar tests on a different cluster:

Node size: 64 cores, 440 GB RAM, 4 GPUs
Number of nodes in cluster: 3

Spark configs:

Driver cores: 8
Driver memory: 50g
Executor cores: 8
Executor memory: 50g
Number of Executors: 12

The executors keep failing because of the following error:

```
21/06/29 22:03:39 ERROR RapidsExecutorPlugin: Exception in the executor plugin
java.lang.IllegalArgumentException: Spark GPU Plugin only supports 1 gpu per executor
	at com.nvidia.spark.rapids.GpuDeviceManager$.getGPUAddrFromResources(GpuDeviceManager.scala:111)
```
I also see this in the beginning on all executor logs:

```
21/06/29 22:03:39 INFO ResourceUtils: ==============================================================
21/06/29 22:03:39 INFO ResourceUtils: Resources for spark.executor:
gpu -> [name: gpu, addresses: 0,1,2,3]
21/06/29 22:03:39 INFO ResourceUtils: ==============================================================
```
Are there some special configurations to avoid this? Since it's a 3 node cluster, where each node has 4 GPUs, I would presume 12 executors is the right Spark configuration (4 executors per node * 3). Please let me know if I'm missing something. Thanks in advance!

**Comment by jlowe** [comment]
> Is this because Spark RAPIDS supports only 1-1 mapping between executor and GPUs?

Yes.  As you saw in the exception message in the other cluster configuration, the RAPIDS Accelerator only supports a 1-to-1 mapping between executors and GPUs.  This topic is discussed in the [FAQ](https://nvidia.github.io/spark-rapids/docs/FAQ.html#why-are-multiple-gpus-per-executor-not-supported).

> How is this enforced on the Spark side?

Normally Spark would schedule GPUs to executors using GPU resources (e.g.: via a configuration setting like `spark.executor.resource.gpu.amount=1`).  If Spark has not been configured to request a GPU per executor then it is the responsibility of the user to ensure each executor is assigned a GPU using some other mechanism.

When using the RAPIDS Accelerator, each executor will attempt to locate its assigned GPU on startup.  In the other cluster configuration case it discovered too many GPUs available to the executor, so it was not sure which GPU should be used.  I'm wondering if the second cluster is running without container isolation and therefore each executor on the node can see all the GPUs on the node.  If that's the case, please see the getting started section for [running on YARN without isolation](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation) for tips on how to help the executor find its corresponding GPU and avoid colliding with other executors on the same node.

**Comment by Niharikadutta** [comment]
Thanks @jlowe for the quick response! 
> Normally Spark would schedule GPUs to executors using GPU resources (e.g.: via a configuration setting like 
> `spark.executor.resource.gpu.amount=1`. If Spark has not been configured to request a GPU per executor then it is the 
> responsibility of the user to ensure each executor is assigned a GPU using some other mechanism.
So this means if the number of executors requested exceeds the number of GPUs on the cluster, it is expected for the equivalent number of executors to be spun up and Spark ignores the remaining executors?

> If that's the case, please see the getting started section for running on YARN without isolation for tips on how to help the executor find its corresponding GPU and avoid colliding with other executors on the same node.
I have set every other config on the documentation for [running on YARN without isolation](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation) except `spark.resources.discoveryPlugin=com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin`, I am testing now with that. Thanks!

**Comment by jlowe** [comment]
> So this means if the number of executors requested exceeds the number of GPUs on the cluster, it is expected for the equivalent number of executors to be spun up and Spark ignores the remaining executors?

If too many executors start on a node then one of two things will happen.

One possibility is an excess executor will be unable to find a GPU to use via the GPU resource discovery script and it will exit with an error.  The driver will attempt to relaunch the executor again.  In that sense it is "ignored" and the relaunch may end up getting scheduled on a node that does have a spare GPU, or it may continually launch and fail while other executors proceed to execute tasks until the application finishes.

Another possibility is that the GPU resource discovery script fails to recognize GPUs already assigned to other processes and incorrectly reports an already occupied GPU as available to the executor.  If the executor fails to initialize on the GPU due to insufficient GPU memory then it will act like the previous scenario.  However if the excess executor is able to successfully initialize and start running tasks, those tasks may run out of GPU memory or cause tasks running in the other process sharing the GPU to encounter OOM errors.  In these cases it can fail the entire Spark job if the errors persist and tasks are unable to complete.

**Comment by Niharikadutta** [comment]
@jlowe Thanks for the explanation, this makes sense. I guess to avoid unpredictable behavior it is best to request the exact same number of executors as are GPUs on the cluster.

About your earlier recommendation, I submitted a job setting the `spark.resources.discoveryPlugin` plugin, and now I'm facing a different error:
```
21/07/01 09:02:54 INFO RapidsExecutorPlugin: Initializing memory from Executor Plugin
21/07/01 09:02:54 ERROR RapidsExecutorPlugin: Exception in the executor plugin
java.lang.IllegalArgumentException: The initial allocation of 1319.9619140625 MB (calculated from spark.rapids.memory.gpu.allocFraction (=0.9) and 1466.625 MB free memory) was less than the minimum allocation of 4031.90625 (calculated from spark.rapids.memory.gpu.minAllocFraction (=0.25) and 16127.625 MB total memory)
	at com.nvidia.spark.rapids.GpuDeviceManager$.computeRmmInitSizes(GpuDeviceManager.scala:181)
```
Could you please guide me about the memory configuration rules for executors, here is the configuration I was requesting:
```
driverMemory: 50g
driverCores: 8
executorMemory: 50g
executorCores: 8
numExecutors: 12
```
To refresh your memory, this is my cluster configuration
```
Node size: 64 cores, 440 GB RAM, 4 GPUs
Number of nodes in cluster: 3
```
The only Spark RAPIDS configuration I have set are these
```
spark.plugins com.nvidia.spark.SQLPlugin
spark.rapids.sql.enabled true
spark.rapids.shims-provider-override com.nvidia.spark.rapids.shims.spark312.SparkShimServiceProvider
spark.rapids.sql.concurrentGpuTasks 2
spark.executor.resource.gpu.amount 1
spark.executor.resource.gpu.discoveryScript /opt/spark/examples/src/main/scripts/getGpusResources.sh
spark.jars /path/to/rapids-4-spark_2.12-21.06.0-SNAPSHOT.jar,/path/to/cudf-21.06.1-cuda11.jar
spark.resources.discoveryPlugin com.nvidia.spark.ExclusiveModeGpuDiscoveryPlugin
```

**Comment by jlowe** [comment]
> now I'm facing a different error:
> `The initial allocation of 1319.9619140625 MB (calculated from spark.rapids.memory.gpu.allocFraction (=0.9) and 1466.625 MB free memory) was less than the minimum allocation of 4031.90625 (calculated from spark.rapids.memory.gpu.minAllocFraction (=0.25) and 16127.625 MB total memory)`

This error most likely indicates you are accidentally sharing a GPU between executors.  What the message indicates is that the executor was only able to allocate just over 1GB of available memory on the GPU which is lower than the minimum fraction config.  That latter config is designed to catch scenarios where a user is likely accidentally running on a GPU that's already in use and therefore probably will crash tasks in the new executor and/or cause problems for the other process using the GPU.

You can check the executor logs for a message that starts with: `Initializing RMM` and ends with the GPU ID that it is using.  It would be good to check whether or not you see two executors running at the same time that say they're using the same GPU ID.  That would be not good, and would explain the very low available memory on the GPU for the executor that led to the error message.  If that's not the issue then you might want to check via something like `nvidia-smi` whether there are other processes on that GPU.

Since you mentioned there's no isolation in your cluster environment, are you running with some kind of mechanism that will prevent to processes from trying to use the same GPU simultaneously?  If possible, we recommend configuring the GPUs for process-exclusive mode which will prevent this, as discussed in the [running on YARN without isolation](https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html#yarn-without-isolation) section.  If you're unable to setup process-exclusive mode on the GPUs then the GPU discovery script must somehow detect which GPUs are in-use and figure out how to atomically allocate a GPU for the executor.  This could be done via lock files in a shared filesystem between the executors, for example, but this is not something the example discovery script does.

> To refresh your memory, this is my cluster configuration

I noticed there's 440GB of RAM and 64 cores per node, and this is sufficient to run 8 executors per node if we're only scheduling on CPU cores and RAM requirements, as the executors only request 50GB of memory and 8 cores.  Is the cluster also scheduling for GPUs?  If not, you run the risk of more than 4 executors running on the same node which would exceed the available GPU count.

**Comment by viadea** [comment]
Just talked with @Niharikadutta . We believe one step is missing for the "YARN without isolation" section which is to run:
```
Foreach GPU index set it to EXCLUSIVE_PROCESS mode:
    nvidia-smi -c EXCLUSIVE_PROCESS -i $index
```

**Comment by Niharikadutta** [comment]
Thanks @viadea and @jlowe , I'm making the changes and running another job, will update the results.

**Comment by Niharikadutta** [comment]
Thanks @viadea and @jlowe, setting exclusive mode for the GPUs resolved the issue.
