### ISSUE TITLE
[FEA] [Audit] - [SPARK-36030] Support DS v2 metrics at writing path

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#3225]
**Is your feature request related to a problem? Please describe.**
Metrics was added in https://github.com/apache/spark/commit/86d1fb4698 . We need to update GpuFileFormatDataWriter.scala as we had copied the code from FileFormatDataWriter.scala earlier.

**Comment by tgravescs** [comment]
the regular file based datasourcev2 write path is disabled in Spark right now so doesn't apply to our code at this point, it only applies to tables and custom sources.  I don't see that this is needed until they enable that and we support or we have other datasource v2 writers that we want to use it.  If they changed something that broke compilation that will be obvious and we can fix, otherwise not needed.
