### ISSUE TITLE
[FEA] GpuGetMapValue should support all valid value data types and non-complex key types

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#3245]
**Is your feature request related to a problem? Please describe.**
When looking up an entry in a map in Spark SQL, we support looking up by literal strings only as in `my_map["key_value"]`. We do not support using other types of expression as the key value. For example, we can't reference a column name as in `my_map[key_column]`.

**Describe the solution you'd like**
We should support all possible data types for values, and non-complex types for keys.  Bonus points if we can support structs as keys. It really comes down to being able to compute equality on the keys.

This depends on https://github.com/rapidsai/cudf/issues/9109

**Describe alternatives you've considered**
N/A

**Additional context**

We need to change GpuOverride type signatures for `GetMapValue` and `ElementAt` with the supported data types.

We will need to implement the following method in GpuGetMapValue:

```scala
override def doColumnar(lhs: GpuColumnVector, rhs: GpuColumnVector): ColumnVector =
  throw new IllegalStateException("This is not supported yet")
```

Here is a proposed test:

```python
@pytest.mark.parametrize('map_gen', [simple_string_to_string_map_gen], ids=idfn)
@pytest.mark.parametrize('key_gen', [StringGen(pattern='key_[0-9]', nullable=False)], ids=idfn)
def test_simple_get_map_value_scalar_key(map_gen, key_gen):
    data_gen = [('a', map_gen), ('b', key_gen)]
    assert_gpu_and_cpu_are_equal_collect(
            lambda spark : gen_df(spark, data_gen).selectExpr(
                'a[b]'))
```

**Comment by andygrove** [comment]
@revans2 I filed this after misunderstanding a comment from you on another PR. Is this valid at all or should we just close it?

**Comment by revans2** [comment]
> @revans2 I filed this after misunderstanding a comment from you on another PR. Is this valid at all or should we just close it?

This is still 100% valid. I have it on my list to go back and figure out/file issues to support maps better.  Right now we are looking at structs mostly.

That said we could have, and still can, make the map get cuda code more generic, so we can produce a gather map, and then use the gather map to get any map value we care about.

But I would almost rather have us try to figure out a way to do this more generically with AST to create the gather map. I think that would give us a lot more flexibility in the future. The problem is that AST does not support strings and it does not support structs, so we need to have some design discussions with CUDF to figure out the right way to do this.

**Comment by revans2** [comment]
I split off the complex map keys into a separate issue as it is likely to be difficult to do and will not be done in the 21.10 time frame.

**Comment by revans2** [comment]
I filed https://github.com/rapidsai/cudf/issues/9109 as the dependency in CUDF
