### ISSUE TITLE
[BUG] 3.2.0 shim: ShuffledBatchRDD.scala:141: match may not be exhaustive.

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#3372]
**Describe the bug**
3.2 has a new partition spec we don't handle in the plugin
```
ShuffledBatchRDD.scala:141: match may not be exhaustive.
It would fail on the following input: CoalescedMapperPartitionSpec(_, _, _)
[WARNING] [Warn] /home/gshegalov/gits/NVIDIA/spark-rapids/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/execution/ShuffledBatchRDD.scala:165: match may not be exhaustive.
It would fail on the following input: CoalescedMapperPartitionSpec(_, _, _)
```

**Steps/Code to reproduce bug**
build the 3.2 shim using 
```bash
$ mvn clean package -Dbuildver=320 -Dskip -DskipTests -pl integration_tests -am 
```

**Expected behavior**
Build must not have semantically significant warnings

**Environment details (please complete the following information)**
 local

**Additional context**
#3323

**Comment by revans2** [comment]
@gerashegalov It looks like the only way to fix this is to add the match to the shim layer.  I think if I do this I can remove `ShuffleManagerShimBase`. Do you have an alternative that would be cleaner? I really don't want to split the match up into if/else blocks because then we would not get warning or errors when some of these change.

**Comment by gerashegalov** [comment]
@revans2 +1 on your approach
