### ISSUE TITLE
[BUG] Integration Cache tests fails for Boolean values

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#350]
**Describe the bug**
Adding join operations that include null values cause the tests to fail. 

**Steps/Code to reproduce bug**
Just run the cache_test.py with --runxfail. 

**Expected behavior**
Test should pass

**Comment by revans2** [comment]
I did a little digging and it looks like it is related to either the cache itself, or in how the data from the cache is copied onto the GPU.  If I disable the cache the test passes.  It is not related to the sort order stored in the cache, because the plan will resort the data after.  It looks like in a few cases a Null value is being placed on the GPU as a false.

**Comment by sameerz** [comment]
Moving out of the release, pending a fix from https://issues.apache.org/jira/browse/SPARK-32672 .
