### ISSUE TITLE
[BUG] Basic Spark join queries failing with RAPIDS accelerator

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3509]
**Describe the bug**
Simple Spark queries like joins are failing with the following error:

```
java.lang.ClassCastException: org.apache.spark.sql.vectorized.ColumnarBatch cannot be cast to org.apache.spark.sql.catalyst.InternalRow
```
We can get it to work by setting either of the following Spark configurations:
`spark.sql.optimizer.dynamicPartitionPruning.enabled = false`
OR
`spark.sql.codegen.wholeStage = false`

Also this issue is reproducible with both v21.06.1 and v21.08.0.

**Steps/Code to reproduce bug**
We are seeing this issue with running a simple query as follows:

```
select count(*)
     from store_sales, date_dim d1
     where ss_sold_date_sk = d1.d_date_sk
       and d1.d_year between 1999 AND 1999 + 2
```

**Expected behavior**
Job should run successfully without needing to disable WholeStage CodeGen and Dynamic Partition Pruning.

**Environment details**
 - Environment location: YARN, Azure Synapse
 - Spark configuration settings related to the issue: Spark 3.1.2 (custom distro)
 - RAPIDS version: 21.06.1 and 21.08.0
 - CuDF versions: 21.06.0 and 21.08.2

**Additional context**
This is being run with our internal Spark distro, and we would need some help in identifying the incompatibility.

**Comment by revans2** [comment]
I have not been able to reproduce this outside of Azure Synapse. I have tried with Spark 3.1.2 and Spark 3.2.0 (pre-release)  I have tried with multiple combinations of AQE and DPP configs.  Regular vanilla Apache Spark does not appear to insert DPP into the query at all.  At this point it appears that this is an optimization that is specific to the custom distro. So to be able to further debug this we are going to need to be on Synapse to do anything.  I am not taking this issue on right now, just adding in some extra information.

**Comment by Niharikadutta** [comment]
Thanks @revans2 for looking into this. Would you mind sharing the event and driver logs of the above investigations you ran against vanilla Apache Spark 3.1.2 if you still have them available?

**Comment by revans2** [comment]
Here are sanitized logs that I just ran.

[logs.zip](https://github.com/NVIDIA/spark-rapids/files/7212279/logs.zip)

I ran in 3 different combinations (please check in the event logs to verify that I got that correct)

app*-0000 was with `--conf 'spark.sql.adaptive.enabled=true' --conf 'spark.sql.optimizer.dynamicPartitionPruning.enabled=true'`
app*-0001 was with `--conf 'spark.sql.adaptive.enabled=false' --conf 'spark.sql.optimizer.dynamicPartitionPruning.enabled=true'`
app*-0002 was with `--conf 'spark.sql.adaptive.enabled=true' --conf 'spark.sql.optimizer.dynamicPartitionPruning.enabled=false'`

All of them were against Spark 3.1.2 in standalone mode on a single node (my desktop). They are against 21.10-SNAPSHOT of the plugin. I will try it with 21.08, but I don't think that has changed enough to matter.  They are also against a TPCDS data set at scale factor 200. I am not sure what the size of the data set was that you used. The scale factor might impact the join so that Spark thinks it is a broadcast join for the date_dim table, but that table does not grow much compared to store_sales.  I also tried before with setting the broadcast threshold very low and it still didn't have any issues.

**Comment by revans2** [comment]
Yup I just ran with 21.08 and it gave the exact same result.

**Comment by Niharikadutta** [comment]
Thanks @revans2 for these logs and the detailed testing. I'll investigate against our distro and get back.

**Comment by viadea** [comment]
@Niharikadutta Is this fixed after using custom build rapids-4-spark jar?

**Comment by Niharikadutta** [comment]
Resolving this issue since this is related to changes in DPP in our custom Spark distro. Will follow up when we have concrete work items for Spark RAPIDS.
