### ISSUE TITLE
[QST] Exposing the GPU operator exec classes to user

### ISSUE THREAD

**Issue by Niharikadutta** [NVIDIA/spark-rapids#3873]
**What is your question?**
I'm trying to use the following classes for checking the RAPIDS overridden physical plan (for internal validations that Spark jobs are using RAPIDS acceleration as expected):

```
GpuProjectExec,GpuHashAggregateExec,GpuColumnarToRowExec,GpuRowToColumnarExec,GpuBroadcastHashJoinExec
```

And I can see these classes as a part of the v21.10 jar:
![image](https://user-images.githubusercontent.com/8151864/138226696-ee98d264-b537-4c15-9975-58e2b6b51c56.png)

![image](https://user-images.githubusercontent.com/8151864/138226748-357e05e2-a129-48c8-94d7-5028920935b7.png)

However on importing these classes I see the following error:

```
error: object GpuProjectExec is not a member of package com.nvidia.spark.rapids
       import com.nvidia.spark.rapids.{GpuProjectExec,GpuHashAggregateExec,GpuColumnarToRowExec,GpuRowToColumnarExec}

error: object shims is not a member of package com.nvidia.spark.rapids
       import com.nvidia.spark.rapids.shims.v2.GpuBroadcastHashJoinExec

```

Can we have these classes loadable outside of the catalyst by the user?

**Comment by Niharikadutta** [comment]
@gerashegalov , @tgravescs Can we look into the below as suggested by Gera:
```
 We could add some def ensureXYZ(plan: SparkPlan) to SparkShims (or a dedicated trait) and then calling it will be safe across classloader boundaries.
```
While trying to add the operator exec classes, I'm seeing it depends on a lot of classes like `com.nvidia.spark.rapids.GpuExec`, `com.nvidia.spark.rapids.Arm`, etc. I'm not sure what is the complete list of all classes that need to be added to [https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/dist/unshimmed-common-from-spark301.txt](https://github.com/NVIDIA/spark-rapids/blob/branch-21.12/dist/unshimmed-common-from-spark301.txt) file, to get this to work. Could you please help with this for the time being, till we have a more robust long-term solution for this?

**Comment by tgravescs** [comment]
If the dependencies are a lot there, then you might just end up with most of the classes being in there, which seems like a lot of work.
So how many API's are you using?  I think there are a few options here.

1) if not very many, seems like just changing your test code to use Strings or something would be less work.
2) Is this run as a notebook or are you pre-compiling the tests?  If pre-compiling you might be able to build that against the aggregator jar but then run against the official dist jar in your image because the classloader would have loaded the classes you need by then.

**Comment by Niharikadutta** [comment]
Got it, thanks @tgravescs we will proceed with using Node strings to validate, closing this issue.
