### ISSUE TITLE
[FEA]Upgrade the hadoop-common hadoop-client  version

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids#4219]
Our plugin is using hadoop-common:2.7.4 hadoop-client 2.7.4 currently, however Spark 3.0 and 3.2 are using hadoop-common-3.2.0 and hadoop-client-api:3.3.1 separately.
It will be better to upgrade it to hadoop-common-3.2.0 hadoop-client-3.2.0
For version 3.0.1 the dependency path: 
   spark-hive 3.0.1 -> spark-core 3.0.1 -> hadoop-client 2.7.4 -> hadoop-common 2.7.4

**Comment by jlowe** [comment]
The plugin uses whichever hadoop-common and hadoop-client versions Spark uses.  We do not want to depend on a specific Hadoop version, otherwise we would need to pull it into the plugin jar and shade it to avoid conflicting with the version provided by Spark.

Therefore I'm not exactly sure what this issue is requesting.  Outside of the tools module, we do not directly depend on Hadoop jars and therefore cannot upgrade them.  I do not think we should start pulling in explicit Hadoop jar versions per the discussion above.  If the desire to upgrade is related to fixing an issue then I think I'd rather see us try to resolve the issue in the shims rather than pull in Hadoop jars and shading them.

**Comment by res-life** [comment]
OK, got it. It's not related to an issue.

**Comment by jlowe** [comment]
Closing this per the discussion above.
