### ISSUE TITLE
[FEA] Audit: OrcFileFormat reader has some configs that needs to be revisited 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#443]
OrcFileFormat.scala has SARG_PUSHDOWN config that we are not taking into account in the GPU version.

**Comment by jlowe** [comment]
This is being handled in the GPU version, just not via that config variable.  This isa config that is used to convey the predicate pushdown from the file format instance to the reader instance which is in a different project.  Note that `SARG_PUSHDOWN` is setup by `buildReader` [here](https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/orc/OrcFileFormat.scala#L143) to convey the filter to the Java ORC reader code.

The plugin does not use `OrcFileFormat` nor the Java ORC reader code and instead handles the predicate filter a bit differently.  See `GpuOrcReaderPartitionFactory` and how it handles the predicate pushdown filters for details on how that is handled in the plugin.  We don't need to honor `SARG_PUSHDOWN` because it's not a config expected to be set by the end-user and we're not going through the code paths that would read or write this config.

**Comment by jlowe** [comment]
@razajafri can we close this?

**Comment by kuhushukla** [comment]
Closing this per Jason's comment.
