### ISSUE TITLE
[DOC] udf-examples.md links broken on nvidia.github.io

### ISSUE THREAD

**Issue by mattf** [NVIDIA/spark-rapids#4507]
## Report incorrect documentation

**Location of incorrect documentation**

https://nvidia.github.io/spark-rapids/docs/additional-functionality/rapids-udfs.html

broken links for -

- RapidsUDF
- udf-examples
- URLDecode x3
- URLEncode x3
- CosineSimilarity
- StringWordCount

**Describe the problems or issues found in the documentation**

all these links use `../..` relative paths for their destination, which works when browsing the source in the github.com/NVIDIA/spark-rapids repository but does not work when browsing the documentation published to nvidia.github.io/spark-rapids

**Suggested fix for documentation**

i expect links to work in both github.com/NVIDIA/spark-rapids as well as on nvidia.github.io/spark-rapids

**Comment by viadea** [comment]
@jlowe @sameerz 
To fix this issue, I plan to use the branch link for the source code in the dev branch(say branch-22.02). 
For example:
```
[udf-examples](https://github.com/NVIDIA/spark-rapids/tree/branch-22.02/udf-examples)
```
How do you think?

If you agree, it means, each time when creating a new dev branch, we just change the version at that time.

How do you think about this solution?

**Comment by jlowe** [comment]
> I plan to use the branch link for the source code in the dev branch(say branch-22.02).

There are two significant drawbacks to that approach:
- We would need to remember to update the link every time we create a new release
- For those browsing the docs via github pages, the link would take them out of github pages rather than to the corresponding documentation on github pages.

I hope we can find a better solution that links to github if you're browsing on github and github pages if you're browsing on github pages and does not require an update every release.

**Comment by viadea** [comment]
closed.
