### ISSUE TITLE
Premerge build takes too long again (over 3 hours)

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4538]
**Describe the bug**
The premerge build for pull requests takes over 3 hours again, it would be nice if it took less time.

investigate why its taking so long.
Perhaps we can drop support for some versions?  Spark should be releasing some new minor versions soon.

**Comment by pxLi** [comment]
For most spark versions in pre-merge we only do build w/o test, so they should not cost too much time.

IMO most time comes from new tests/cases we added to integration tests, may be we can shrink the data_gen size in pre-merge only?

**Comment by jlowe** [comment]
We've added a lot of tests that have tons of dimensions, and that adds a ton of tests to run.  For example, some of the slower tests are joins, and those test across the dimensions of join types, data types, and batch sizes (if not even more dimensions in some specific cases).  We may want to consider if some of these test combinations are not worth the cost it is taking to run them.  For example, do we really need to test every join type and every data type for a batch size of 100 (which is quite slow to run), or is it sufficient just to test one or just a handful of join types and data types for that extreme configuration?

Executive summary is that I think we need to audit which test files and individual tests are taking the longest and then see if we really need to run all the dimensions on those tests to get a satisfactory level of coverage from them.

**Comment by revans2** [comment]
I think that there are a few things happening.  We have some tests that are slow because we are doing exhaustive combinations.  We have other tests that are slow because we are doing a lot of computation. I totally agree that we probably don't need all combinations. We probably also don't need to cover as much data in the pre-merge which might reduce the amount of computation. But before we get into any of this we probably want to measure to see what each problem really is instead of just guessing.

Do we have stats somewhere about how long each test is taking? It looks like we can add `--durations=N` to the command line when running the tests and it will tell us the top `N` longest running tests, or 0 if we want to see all of them, but with a min time cutoff that is set by `--durations-min`. So we could get an idea about what is actually happening, and it can let us also test on a subset of the tests to see if our efforts would help without having to run all 3 hours of tests each time we want to make a change and see if it helped.

My guess is that both of you are right.  We have some tests that we know are very long running and we can probably turn off some versions of them without much hit to coverage. There are probably also a lot of really small tests. I am not sure if we drop the size of the data how big of an impact that will have. 

I personally am more inclined to throw more hardware at the problem.  Can we run the integration tests in 2 containers instead of 1?  We are adding in more functionality all of the time. So is Spark. Neither of these are going to change any time soon, at least no as long as the projects are still viable.  So just doing a quick cleanup of tests is good, but I don't think we will be able to constantly find more tests to throw away. We need to go to a model where we can actually scale the hardware with the testing requirements.

**Comment by sameerz** [comment]
First steps here are to identify the tests that are taking a long time.

**Comment by pxLi** [comment]
also cc @zhanga5 for the latest case-level stats

**Comment by zhanga5** [comment]
with `--junitxml=xxx` pytest can create junit-xml style report and if collect on Jenkins we would be able to view test result info including detail case list, duration, even trend etc. Test PR https://github.com/pxLi/spark-rapids/pull/228 was created and generated one sample report on Jenkins: http://nv/2su (need vpn)

![image](https://user-images.githubusercontent.com/13271672/150282478-be84b529-9f74-4195-b302-8d35d12f545b.png)

As expected we can tell `join_test` took longest time (>5h in total, note, this accumulated test cases cost in parallel testing) with exhausted cases (2,650). We could further look into `join_test` and tell which cases are most time consuming. I would suggest enable this test report all the time in order to evaluate and balance test scope & time cost easily.

![image](https://user-images.githubusercontent.com/13271672/150283869-ffae9747-a56e-4ab5-97a2-b9b132062ac7.png)

**Comment by revans2** [comment]
+1 on enabling the test report all the time.  No reason not to.

Now we need someone to look at the tests propose a plan on which tests we should stop doing. It is fairly clear that we probably don't need to do all of the tests for `test_cartesian_join_special_case_count[100`. But I think there are likely to be others too.

**Comment by zhanga5** [comment]
OK, will enable such test report first

**Comment by jlowe** [comment]
Build time is well under3 hours, and we're about to remove quite a few builds for the 30x shims (see #4915).  Closing this for now.  We can reopen or file a new one if this becomes a major issue again.
