### ISSUE TITLE
[FEA] Support UCX shuffle with optimized AQE

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#455]
**Is your feature request related to a problem? Please describe.**
In order to support AQE more fully, we are introducing shuffle changes [1] that are not compatible with the UCX shuffle logic and we need to resolve this before enabling UCX and AQE together.

[1] https://github.com/NVIDIA/spark-rapids/pull/319

**Describe the solution you'd like**
We should be able to use UCX and AQE together.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abellina** [comment]
@andygrove pointed me at this PR that has been merged into master: https://github.com/apache/spark/pull/29307. I think this likely addresses the "reader with nothing to do" concern I had. I am adding it to this issue.

At a minimum we need to test with the 3.1 shim (since 3.1 would carry this change), and then hopefully it gets backported to 3.0.1 so we can enable it in that as well. I'd like to sign up for this if that's OK @andygrove.

**Comment by abellina** [comment]
The issue has been backported: https://github.com/apache/spark/pull/29321
