### ISSUE TITLE
jenkins integration build timed out at 10 hours

### ISSUE THREAD

**Issue by tgravescs** [NVIDIA/spark-rapids#4675]
**Describe the bug**
It looks like our integration build that tests the stable versions of Spark timed out after 10 hours. It looks like we do builds in 3 different stages and within those stages things are parallel. But I think that will means we get 3 times the max test time. It looks like each of those is taking like 3.5 hours so we hit the timeout.  I will increase the timeout for now but we may want to find a better way to do this.

**Comment by tgravescs** [comment]
cc @pxLi @NvTimLiu

**Comment by tgravescs** [comment]
also note the prerelease build only seems to be taking about 8 hours so not sure what diff is there

**Comment by pxLi** [comment]
I have checked the test logs, since we have some logic to auto decide the parallelism of the tests, https://github.com/NVIDIA/spark-rapids/blob/branch-22.02/jenkins/spark-tests.sh#L257-L262
if its > 7 (w/ larger gpu mem), the total runtime would actually spend 40-60 mins comparing to <= 7.

The reason why prerelease looks fine is due to we always use T4 to test all binaries, but for dev one since we do not have so many resources, we leverage a pool of multiple-type gpus, so some test could go on T4, other could go on A30/A100 one which increased the parallelism to 8.

I will update the upper limitation to 7

**Comment by pxLi** [comment]
close this for now. If we see this again after more tests cases, we can create another issue
