### ISSUE TITLE
data size of GPU shuffle write is less than that of CPU ? [QST]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#472]
when I run TPC-DS query-13 on GPU  , I found that the stage shuffle write data size is 528G，but when I run it on CPU, the same stage shuffle write data size is 770G+ , and the input data row is same ,part of DAG as : 

<img src= "https://user-images.githubusercontent.com/33319780/88934910-c1c34400-d2b3-11ea-8138-8c13b58bd6dc.png" width="40%" height="40%"><img src= "https://user-images.githubusercontent.com/33319780/88934934-c851bb80-d2b3-11ea-8e97-fcf4c714f909.png" width="50%" height="50%">
my question is that : 
1 . why gpu shuffle write data size is less that cpu ? Because the compression algorithm is different ？ because shuffle data format  is  column ,and  data size is less than row data of cpu  shuffle ?  
2 . it's said that gpu is not suport GpuSortMergeJoinExec ？ Is there a schedule to support this operator ？

workload : TPC-DS QUERY-13
query-13 : 
SELECT avg(ss_quantity), avg(ss_ext_sales_price), avg(ss_ext_wholesale_cost), sum(ss_ext_wholesale_cost) FROM store_sales , store , customer_demographics , household_demographics , customer_address , date_dim WHERE s_store_sk = ss_store_sk AND ss_sold_date_sk = d_date_sk AND d_year = 2001 AND ((ss_hdemo_sk = hd_demo_sk AND cd_demo_sk = ss_cdemo_sk AND cd_marital_status = 'M' AND cd_education_status = 'Advanced Degree' AND ss_sales_price BETWEEN 100.00 AND 150.00 AND hd_dep_count = 3 ) OR (ss_hdemo_sk = hd_demo_sk AND cd_demo_sk = ss_cdemo_sk AND cd_marital_status = 'S' AND cd_education_status = 'College' AND ss_sales_price BETWEEN 50.00 AND 100.00 AND hd_dep_count = 1 ) OR (ss_hdemo_sk = hd_demo_sk AND cd_demo_sk = ss_cdemo_sk AND cd_marital_status = 'W' AND cd_education_status = '2 yr Degree' AND ss_sales_price BETWEEN 150.00 AND 200.00 AND hd_dep_count = 1 )) AND ((ss_addr_sk = ca_address_sk AND ca_country = 'United States' AND ca_state IN ('TX', 'OH', 'TX') AND ss_net_profit BETWEEN 100 AND 200 ) OR (ss_addr_sk = ca_address_sk AND ca_country = 'United States' AND ca_state IN ('OR', 'NM', 'KY') AND ss_net_profit BETWEEN 150 AND 300 ) OR (ss_addr_sk = ca_address_sk AND ca_country = 'United States' AND ca_state IN ('VA', 'TX', 'MS') AND ss_net_profit BETWEEN 50 AND 250 )) ").show;

this is my config file : 
[cpu-config.txt](https://github.com/NVIDIA/spark-rapids/files/5001839/cpu-config.txt)
[gpu-config.txt](https://github.com/NVIDIA/spark-rapids/files/5001841/gpu-config.txt)

**Comment by revans2** [comment]
We shuffle the data in a different format so the compression ration can be very different. Most of the time we see smaller shuffles with a columnar shuffle, but there are cases where we have seen it be larger.

**Comment by rui911013** [comment]
by the way,  I need explain that I test cpu with spark.sql.optimizer.dynamicPartitionPruning.enabled = true and spark.sql.adaptive.enabled = true ;
and also I observes a phenomenon that ： when I turn on dynamicPartitionPruning and AQE（spark.sql.adaptive.enabled ） on GPU ， that stage will shuffle write 770G+ data like CPU .

**Comment by revans2** [comment]
We are still working on AQE and typically we are not able to do a columnar shuffle when AQE is enabled.  So it is likely that we still did a row based shuffle in that case.  @andygrove is heading up the AQE work and can probably help you understand what is happening there.

**Comment by revans2** [comment]
As for the sort merge join question that is a harder one.  We don't have any item on the backlog right now, but if you have a use case for it file a feature request describing the exact use case and problem that you are seeing.  Then we can go back to prioritize how to address that use case.

**Comment by revans2** [comment]
Oh I forgot to add that we do support `SortMergeJoinExec`, but we replace it with a `ShuffledHashJoinExec` this really only becomes a problem when you have a skewed join that cannot fit in GPU memory.

**Comment by rui911013** [comment]
> We shuffle the data in a different format so the compression ration can be very different. Most of the time we see smaller shuffles with a columnar shuffle, but there are cases where we have seen it be larger.

thanks a lot ，I have another 2 questions：
1. Can you describe in detail the issues related to shuffle data format? Is compression supported now?
2. In addition, it should be noted that we do not use shuffle plugin now. If we do not have RDMA, will shuffle plugin work ？

**Comment by revans2** [comment]
To answer your question you need to understand that there really are three different shuffles that can show up in a plan.

1) The row based shuffle that happens for all CPU processing. This essentially dumps out the in memory format for unsafe rows and uses the configured compression library to compress it. This is what you see any time there is an `Exchange` in the plan.
2) The columnar based shuffle that happens for all `GpuColumnarExchange` nodes when not using the shuffle plugin.  This does the same thing as the row based CPU shuffle, but instead of writing the data out in the InternalRow format it writes the data out in an arrow-ish format, which we may switch to arrow at some point.  It still relies on the CPU to compress the data using the configured compression library and store it. This shuffle works anywhere that the SQL plugin works, which is why it is on by default.
3) The Shuffle Plugin, which is configured separately. This is where you can get the RDMA transfers if you have UCX configured properly to do them. There is no compression for this yet, but we are working on it.  Because this relies on UCX to do the transfers you can use essentially all of the transports that UCX supports, so if you don't have RDMA you could configure it to use TCP/IP, but we have not really been testing that so the performance and stability is a bit less known right now.

**Comment by JustPlay** [comment]
@revans2

An another question need your help，

We want to eval the time for the shuffle phase (only shuffle write and shuffle read, not include the upstream or downstream computing or IO), where should we add sql-metrics or time-counting point in the code (both for Exchange shuffle and GpuColumnarShuffle)

**Comment by revans2** [comment]
I don't remember exactly when we grab/release the GPU semaphore during the columnar exchange. I know that we release it after we have copied the data off of the GPU and that we grab it before we copy data onto the GPU.  I think it is in the serialization plugin for the shuffle, but I would have to look it up to be sure.

As for measuring the shuffle time, that is kind of hard and you probably want to look at SortShuffleManager, which is the default ShuffleManager in spark. In regular spark it is doing row at a time processing, so it is really hard to get an accurate measurement of the shuffle independent of the other processing and I/O, because it is all intermixed. I think your best bet in those cases would be to try and use a sampling profiler to see how much of the time is spent in different parts of the code, and see how much is spent in the code that is related to shuffle.  This is not perfect because the read operations happen in the thread pool and can overlap with each other.

**Comment by JustPlay** [comment]
> We shuffle the data in a different format so the compression ration can be very different. Most of the time we see smaller shuffles with a columnar shuffle, but there are cases where we have seen it be larger.

why columnar shuffle's compression ration is bigger in most case?

**Comment by JustPlay** [comment]
> We are still working on AQE and typically we are not able to do a columnar shuffle when AQE is enabled. So it is likely that we still did a row based shuffle in that case. @andygrove is heading up the AQE work and can probably help you understand what is happening there.

@revans2 @andygrove

(1) I hear rapids-0.2 will support AQE， so if we use rapids-0.2 with AQE enabled，whether the spark/rapids will do a row-based shuffle or a columnar-based shuffle? 
(2) if the spark/rapids-0.2 will do a row base shuffle when AQE=true, whether the overhead of row-based shuffle will eliminate the performance gain by AQE？

**Comment by andygrove** [comment]
@JustPlay With the support for optimized AQE that we are currently working on, any shuffle or broadcast that would run on GPU with AQE off will now run on GPU when AQE is on as well. With the 0.1 release, all shuffle and broadcast exchanges happen on CPU, which I would think outweighs the benefit of AQE in most cases.

**Comment by revans2** [comment]
Closing as no more questions in 4 days

**Comment by chenrui17** [comment]
> We shuffle the data in a different format so the compression ration can be very different. Most of the time we see smaller shuffles with a columnar shuffle, but there are cases where we have seen it be larger.

Recently, some query shuffles are found to be larger than the CPU during the test, such as tpc-ds query-13
I found that the filter operator after scan operator did not filter enough data, but CPU filtered more data： 
cpu dag：
![image](https://user-images.githubusercontent.com/33319780/95724311-cee3b280-0ca8-11eb-956d-04e422ae0f00.png)
while gpu dag：
![image](https://user-images.githubusercontent.com/33319780/95724388-e58a0980-0ca8-11eb-9c9f-58fc46a7f9ed.png)
compared to physical plans :
 
![image](https://user-images.githubusercontent.com/33319780/95724452-f9357000-0ca8-11eb-8eeb-297634555031.png)

so ,What are the possible reasons

**Comment by revans2** [comment]
@chenrui17 it would be best if this was put on a new issue that is not closed, or we might lose track of it.

**Comment by revans2** [comment]
Also when I run the query at scale factor 200 I see the exact same number of outputs for each filter in the query.  You plan appears to have hit DPP, because I see a subquery broadcast.  Did you run the query with any different settings?
