### ISSUE TITLE
integration_tests test jar has integration test code split between src/main and src/test

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#4892]
The `integration_tests` module has code in both `src/main` and `src/test` that is intended for testing the `sql-plugin` module.  This is very confusing and has lead to problems in CI builds that assumed everything needed to perform the integration tests is in the `integration_tests` main jar, see #4890.  Usually code in `src/test/` is intended to test code within that module, and it's inconsistent to place code for integration testing the RAPIDS Accelerator in both `integration_tests/src/main` and `integration_tests/src/test`.

**Comment by revans2** [comment]
For background the split was originally intended so that src would produce a standalone jar that only depended on Spark. Then there would just be pure tests inside of the test directory that could depend on the plugin at runtime to be able to verify that things were working. I think that fits with what was described by @jlowe above and I hope we can return to that.
