### ISSUE TITLE
[QST] Performance question 

### ISSUE THREAD

**Issue by eyalhir74** [NVIDIA/spark-rapids#4894]
I'm in the beginning of trying converting our HUGE data/spark code from the CPU to the GPU. While I have vast experience with GPUs/CUDA, I find it a bit hard to pin-point exactly how/what the performance limitations I'm seeing. Furthermore, I'm looking at many queries, with different issues (such as non-supported features, strings, parquet issues etc.)

I've followed all the performance tuning guides and the suggested actions here, still would be happy to get more insights and assistance if possible :)

I am currently looking at the following query. CPU time is roughly the same as the GPU.

`select first(x1, true), 
  first(x2, true), 
  ... 
  first(x26, true),
  sum(case when y1 = 'aa' and y2 then 1 else 0 END),
  sum(case when y1 = 'bb' and y2 then 1 else 0 END)
  where (z1 is null or z1 = false) and (z2 is null or z2 = false) and (z3 is null or z3 = false) and (z4 is null or z4 = false)
  group by some_string_field_up_to_50_chars`

Fields x1 to x26 are either strings or booleans.

Attached is the nvprof output. If I understand correctly 50% of the compute time is string related? and 20% is decoding the PARQUET's page information (i.e. not even decompressing the data itself?)

I guess my questions are:
- Is there some way of improving the query's GPU performance (I've replaced the FIRST operators to MIN, didn't help)
- Can I somehow evaluate if the parquet file/configuration is harming the GPU's performance (I'm running it on a small subset of the data - 100 ~300MB files each for a total of 35GB. Full data is over a Tera)
- Previous answers here suggested running the qualification tool and explain tool. Can I somehow retrieve information if the data being fed to the GPU is too small (because of a mis-configuration/small Parquet files/etc)?

Any further assistance is more than welcomed :)

![Screenshot from 2022-03-02 17-21-50](https://user-images.githubusercontent.com/2410527/156393815-9aaefac0-f412-4014-932b-49caf9ef70f3.png)

**Comment by eyalhir74** [comment]
@jlowe I'm using RAPIDS Accelerator 21.12.0 using cudf 21.12.0
I would be very happy to assist/check our queries if there's a performance enhancement Parquet branch.

Changing the spark.sql.files.maxPartitionBytes and spark.rapids.sql.concurrentGpuTasks didn't provide for a significant performance change.

Going through the explain plan, I see a few non-GPU compliant ops, maybe this can explain the low performance?

As for the last item, regarding the data size fed into the GPU, I wasn't clear about what I thought. I understand that generally saying "this work is too small/big for the GPU" is not trivial/doable. I was thinking more in the lines that RAPIDS would be able to specify how many columns/rows/parquet pages (and any other performance relevant properties) was used and maybe that would give hints as to whether the spark configuration/parquet files are a reason for underutilizing the GPU.. hope it makes sense.

Attached is the plan file for this query. I've replaced all field names as they can't be shared.

Any further ideas, would be greatly appereciated.
[Query.txt](https://github.com/NVIDIA/spark-rapids/files/8176648/Query.txt)

**Comment by eyalhir74** [comment]
Some SparkUI screen shots.

`== Physical Plan ==
CollectLimit (13)
+- * Project (12)
   +- GpuColumnarToRow (11)
      +- GpuHashAggregate (10)
         +- GpuSort (9)
            +- GpuShuffleCoalesce (8)
               +- GpuColumnarExchange (7)
                  +- GpuHashAggregate (6)
                     +- GpuSort (5)
                        +- GpuProject (4)
                           +- GpuCoalesceBatches (3)
                              +- GpuFilter (2)
                                 +- GpuScan parquet  (1)

`

![Screenshot from 2022-03-03 11-45-22](https://user-images.githubusercontent.com/2410527/156539536-ae254b25-cf57-44ae-a1b5-f7e17f1c98a0.png)
![Screenshot from 2022-03-03 11-44-37](https://user-images.githubusercontent.com/2410527/156539541-712701e8-11ed-4b30-aba5-079400b539a5.png)

![Screenshot from 2022-03-03 11-46-51](https://user-images.githubusercontent.com/2410527/156539516-70cc9a2d-464d-496f-b9fb-3540552299e4.png)
![Screenshot from 2022-03-03 11-46-43](https://user-images.githubusercontent.com/2410527/156539523-cea7e2b7-9043-417d-8eb8-7e2f148f5810.png)
![Screenshot from 2022-03-03 11-46-31](https://user-images.githubusercontent.com/2410527/156539528-df00ecd1-9131-4fa9-9494-769112050f0f.png)
![Screenshot from 2022-03-03 11-45-48](https://user-images.githubusercontent.com/2410527/156539532-343a5785-5105-448e-9da3-6140058e8265.png)

**Comment by jlowe** [comment]
> I'm using RAPIDS Accelerator 21.12.0 using cudf 21.12.0

Given the relatively high cost of the contiguous_split kernel from your traces, I suggest updating to the [22.02 release of the RAPIDS Accelerator and cudf](https://nvidia.github.io/spark-rapids/docs/download.html#download-v22020).  That includes some performance fixes for contiguous_split that may help your use-case.

> Going through the explain plan, I see a few non-GPU compliant ops

According to the physical plan and stage runtime statistics, I don't think the impact of this is significant.  The only operations that aren't running on the GPU are the Project and CollectLimit occurring right at the end of the query.  This is the last stage of the job, which appears to have taken only 0.4 seconds, while the main stage took 1.1 minutes.   Also note that the SQL metrics show that only 26,080 rows went through that part, which is a small fraction of the 33+ million rows we started with.

This job appears to be mostly all about the initial stage, and specifically the Parquet load within that stage.  That explains why changing other parts of the query doesn't seem to help much.  Looking at the metrics associated with the Parquet load, buffer time is significant with the average task spending 3.6 seconds just fetching the data from the distributed filesystem, and the GPU takes 305 milliseconds decoding it afterwards.  So I/O overhead seems to be a significant factor for this query, which helps explain the low GPU utilization.

> I was thinking more in the lines that RAPIDS would be able to specify how many columns/rows/parquet pages (and any other performance relevant properties) was used and maybe that would give hints as to whether the spark configuration/parquet files are a reason for underutilizing the GPU

This isn't something that RAPIDS cudf supports reporting back as a side-product of the load, although one could identify those metrics separately via Parquet tools that examine the footer of the Parquet files.  Although given the metrics I'm seeing above, it seems to be more about waiting for I/O than waiting for the GPU.  The metrics show tasks are spending over 10x the time waiting for raw Parquet data from the distributed filesystem rather than waiting for the GPU to decompress and decode it.
