### ISSUE TITLE
[FEA] Add operations from cudf C++

### ISSUE THREAD

**Issue by PerkzZheng** [NVIDIA/spark-rapids#513]
**Is your feature request related to a problem? Please describe.**
I wish the RAPIDS Accelerator for Apache Spark would add more built-in rapids-accelerated operations to Spark, especially those complicated data processing (like replacing low-frequency values, label encoding...). Currently, it is just a idea without any demos. I wish that spark-rapids can not only accelerate SQL operations, and maybe develop a new library (with more functionality, just like python cudf) . If the plugin can provide a scratch from cudf C++ to java about how to add new operations, users can also have chances to develop their own operations.

Spark SQL with rapids-acceleration can be helpful in normal data analysis. However, Spark SQL can not be comparable with python in terms of functionality (pandas, numpy, and so on). 

**Describe the solution you'd like**
Normally, pandas-UDF can be a great way to combine spark scalability and python functionality. How to provide gpu-acceleration for pandas-UDF can be a slightly tricky problem because it concerns about moving data between CPUs and GPUs. 

The spark-rapids plugin is based cudf C++ and Apache Arrow. If we can implement some new gpu-accelerated operations built in the plugin, where users can directly import them, it seems to be more direct way.  

**Describe alternatives you've considered**
GPU-accelerated Pandas-UDF can be an alternative way. It provides more flexibility compared with built-in operations.

**Additional context**
The idea needs more discussion.

**Comment by PerkzZheng** [comment]
After more discussion, I found the spark-rapids plugin can not help develop new operators based on cudf. It is just converting physical plans into gpu-version, instead of "operations".

**Comment by revans2** [comment]
I am not ready to close this just yet.  There is a lot of functionality that cudf offers that is not in Spark yet.  The big difference is distributed processing vs non-distributed.  Pandas/numpy/etc operate in a single process, so the algorithms don't need to think about fault tolerance or how to split the work up into smaller parts that can be done in parallel.  Cudf follows the pandas model and even limits the processing to be within a single GPU.

Spark does have the same flexibility as pandas, but that comes from the RDD API, which we have not been concentrating on because we cannot accelerate it transparently. We wanted a low barrier to entry and no code change was the lowest barrier to entry that we could think of.

Is there a specific set of operations that you care about? Some operations that would act like a [scalar udf](http://spark.apache.org/docs/latest/sql-ref-functions-udf-scalar.html) we should be able to help out exposing if we know what those operations are that are missing.

Other operations that look at all or a subset of the table are harder to do because of the distributed nature of Spark.  We have to find ways to split the algorithm up, and in some cases, we cannot do that without help from cudf itself.  This is why it would be great to understand the exact operations you are looking for.  Is there a specific use case that you have?

**Comment by PerkzZheng** [comment]
I have met some operations that may take great amount of time in data processing, such as replacing low-frequency values for each row.

Replacing low-frequency values means that for each row, we count values and if the count is less than a threshold (let’s say 6), we will replace all the same values with another value we specified.

I have implemented two ways (based on Spark SQL) to deal with it, but the results is still not good compared with applying cudf directly. 
1. window operation
![image](https://user-images.githubusercontent.com/67892460/89424580-8e2c6200-d76a-11ea-86d6-1ef518bf9916.png)
2. 'groupby(row_name).count()', and then do 'join', finally 'when..otherwise'

**Comment by revans2** [comment]
Sorry I have been out for a bit.

There are a few ways that you can rewrite this query to make it more efficient, but generally yes, you are constrained by what spark SQL supports if you want it to run on the GPU.

First off, if the data you are processing fits in the memory of a single host, then you should probably not be using Spark.  Spark is designed for scale out, and even if it can process smaller amounts of data it is likely to be slower than another solution like cudf that can run within a single process and keep all of the data cached on the GPU.  So is there a specific cudf operation that you did that was much faster?

Second,

I did something very similar for DLRM.  

https://github.com/NVIDIA/DeepLearningExamples/blob/1cad1801646dee0e96e344b43c796181d6f05564/PyTorch/Recommendation/DLRM/preproc/spark_data_utils.py

Its goal was primarily to map string columns to numeric columns, but filtering low frequency terms also was an optional part of that too.  The biggest issue with it was that the cardinality of the dictionary was so large that for some columns it didn't even fit in the memory of a single GPU.

I am happy to explain how I did it and the decisions I made, but they are rather specific to that use case and if your data is not as big as mine it might not be worth doing the same things.

**Comment by PerkzZheng** [comment]
@revans2 

Thanks, Robert. It really helped a lot. 
As you said, spark is really designed for scale out. Mutli-times shuffling could be one reason that why replacing low-frequency values for each column could be so slow. The size of datasets could be another reason. 
cudf does run much faster than Spark SQL with GPU-acceleration. I guess I can try more on dask-cuDF if my datasets are not large enough for Spark, and at the same time they can not fit into single GPU memory.

**Comment by revans2** [comment]
That is one option.  It would be great to see the cudf/dask code that you are using.  This is a very common operation in ML and it is something that we, and the spark community, may need to come up with a better way to address.

**Comment by revans2** [comment]
This has been open for a long time with no further movement. I am going to close it, but @sameerz we really should come back to this when SQL support has calmed down and we want to start branching out into other areas of processing.
