### ISSUE TITLE
[FEA] Support array_join

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5223]
I wish we can support function array_join.

Eg:
```
from pyspark.sql.functions import *
df = spark.createDataFrame([(["a", "b", "a"], ["b", "c"]), (["a","a"], ["b", "c"]), (["aa"], ["b", "c"])    ], ['x', 'y'])
df.write.format("parquet").mode("overwrite").save("/tmp/testparquet")
df = spark.read.parquet("/tmp/testparquet")
df.select(array_join(df.x, ".").alias("join")).collect()
```

Not-supported messages:
```
    ! <ArrayJoin> array_join(x#72, ., None) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ArrayJoin
```

**Comment by revans2** [comment]
This is a string operation very similar to casting an array to a String which we already support. I think we should be able to do this without any help from CUDF.

**Comment by ttnghia** [comment]
What is the difference between `array_join` and `concat_ws`?

**Comment by revans2** [comment]
@ttnghia `array_join` appears to be very similar to `concat_ws`. It offers an optional null replacement in addition to the separator. Where as concat_ws always skips nulls and can take either an array or single string values. This should be fairly simple to implement.

**Comment by revans2** [comment]
I have been trying to get this to work and I ran into an issue with https://github.com/rapidsai/cudf/issues/12766

It turns out that there is special case handling of all null lists/arrays, that is different from what Spark does, or what we expect. I can work around it, but it is not going to be sure cheap to even detect that this is happening and it would probably be a lot faster to just fix this.

I plan on doing some testing with concat_ws too because I think the tests there might not be good.
