### ISSUE TITLE
[FEA] Support arrays_zip

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5229]
I wish we can support arrays_zip.

Eg:
```
from pyspark.sql.functions import *
df = spark.createDataFrame([(["a", "b", "a"], ["b", "c"]), (["a","a"], ["b", "c"]), (["aa"], ["b", "c"])    ], ['x', 'y'])
df.write.format("parquet").mode("overwrite").save("/tmp/testparquet")
df = spark.read.parquet("/tmp/testparquet")
df.select(arrays_zip(df.x,df.y).alias("zip")).collect()
```

```
    ! <ArraysZip> arrays_zip(x#72, y#73, x, y) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.ArraysZip
```

**Comment by revans2** [comment]
arrays_zip will make an array of structs as output. If all of the arrays had the same offsets column it would just involve reordering the columns so that the data columns are under a struct column which is under the array column with corresponding offsets, but because of nulls and different length arrays it does not work out of the box. 

We probably can make this work by finding the maximum length of arrays in each row and then creating a segmented gather list to insert the nulls where needed, then gather the child arrays and do the manipulation. We probably don't need cudf for this, but until we really start to write it and see all of the corner cases I don't know for sure.
