### ISSUE TITLE
[FEA][Audit] - [SPARK-34863][SQL] Support complex types for Parquet vectorized reader

### ISSUE THREAD

**Issue by nartal1** [NVIDIA/spark-rapids#5257]
**Is your feature request related to a problem? Please describe.**
 Support for complex types (list, map, array) for Spark's vectorized Parquet reader is added in Spark-3.3. From the PR description, the benchmark shows good speed up when vectorized parquet reader is used for complex types. Need to evaluate the tasks to be done in the plugin to support this. 

Spark commit - https://github.com/apache/spark/commit/deac8f950e

**Comment by revans2** [comment]
We would need to fix any issues with HostColumnarToGpu for nested types. We have avoided this because the Spark APIs when we start to get into structs really only expose rows, which makes it difficult for us to do the conversion efficiently. We probably should look at what we can do to special case the common columnar types OffHeapColumnVector and OnHeapColumnVector that we can reach into and get the data out more cleanly like we do for Arrow.  For the others we might need to convert the data rows first and then put it on the GPU.  That is relatively little code to do this, but it is going to be slower.

**Comment by jlowe** [comment]
> For the others we might need to convert the data rows first and then put it on the GPU. That is relatively little code to do this, but it is going to be slower.

We're already doing this for the nested types in #3961.

As I understand it, there are two, somewhat separate, performance issues to address here.  The first is optimizing HostColumnarToGpu to leverage columnar representations of nested types if possible as @revans2 noted.  The second is updating the ParquetCachedBatchSerializer which is currently using the Parquet readers on the CPU when falling back a cache read to the CPU.  That code should also be updated to leverage a vectorized reader for nested types when that is supported.
