### ISSUE TITLE
[BUG] partitioned writes require single batches and sorting, causing gpu OOM in some cases

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids#5448]
We have seen cases where `GpuInsertIntoHadoopFsRelationCommand` runs OOM while trying to sort data for partitioned writes. The symptom is a task that is reading close to full GPU memory, and ends up having to spill the device store. It runs out of memory with most of the GPU in use.

Possible culprits:

This command [wants a single batch](https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/GpuInsertIntoHadoopFsRelationCommand.scala#L261) and the writer framework says it needs this [while out-of-core sort isn't implemented](https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/sql-plugin/src/main/scala/com/nvidia/spark/rapids/GpuDataWritingCommandExec.scala#L123) (it now is), so we should be able to stop requiring single batch (?). 

It is not clear to me whether the sort is absolutely necessary either. @jlowe pointed out it is likely to not hold open all the parquet writers as we read in batches, but that the sort is the likely issue here. We would need to confirm whether it is needed, or find other ways to handle partitions that are larger than GPU memory of a single executor.

**Comment by revans2** [comment]
When discussing another issue I had the idea that maybe we should skip doing the sort all together. We are sorting because that is what Spark did to be able to group the input data by a specific key. Then they can walk through the data a row a at a time and if the key they care about changes, then they can close the current file, open a new file to write to for this key.

We can assume that the cardinality of these keys should be small so we can probably split each batch as it comes in on each key individuality.  We need to take care to try and keep the relative order of the rows the same within that key. Each of those splits can be tracked in a map and made to be spillable so that when we are ready to write out the data we can walk through the map and write out the data to each file. In the common case (the ideal one) there would be a single key per task so it really would just be doing a contig split on the data and then writing each batch out to after we verified it.

We might even be able to have an optimization that if the amount of data is over some threshold that after doing the split we start to write out the largest split in the first batch so we don't need to worry about spilling it, and we can write out at least a portion of the data each time.

**Comment by res-life** [comment]
The cause is that the input of the `out-of-core`  sort is a single large batch. 
The single large batch caused the OOM.

`out-of-core` sort should not require a single batch, it can pull all the input batches and then sort.
Before the `out-of-core` sort feature was added in,  we do need the single batch for `in-memory` sorting.

Seems we should update the logic after the `out-of-core` feature.

Please see 2 related PRs for details
1. Robert Evans 3/24/20, 10:40 PM Support for partitioned writes
```
  // We need a single batch if we have to sort the data
  override def requireSingleBatch: Boolean = isPartitioned || isBucketed

  // Need single batch in some cases, at least until out of core sort is done
  override def childrenCoalesceGoal: Seq[CoalesceGoal] =
```

2. Robert (Bobby) Evans* 2/22/21, 10:28 PM Add in out of core sort (#1719)

@revans2, help to check

**Comment by revans2** [comment]
@res-life Yes we could do it the way you are suggesting. When I did the out of core work on the other two PRs I started to add this one in too, but it ended up being more complicated than a quick change, so I left it for later. It is likely to be simpler to try and tie the out of core sort into this, but I personally think that https://github.com/NVIDIA/spark-rapids/issues/5448#issuecomment-1124287404 is going to be a better solution. Especially if we are likely to only see one key, we can potentially avoid a lot of memory issues.

**Comment by res-life** [comment]
I got some suggestions from Spark [DynamicPartitionDataConcurrentWriter](https://github.com/apache/spark/blob/v3.3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileFormatDataWriter.scala#L374-L387)
```
/**
 * Dynamic partition writer with concurrent writers, meaning multiple concurrent writers are opened
 * for writing.
 *
 * The process has the following steps:
 *  - Step 1: Maintain a map of output writers per each partition and/or bucket columns. Keep all
 *            writers opened and write rows one by one.
 *  - Step 2: If number of concurrent writers exceeds limit, sort rest of rows on partition and/or
 *            bucket column(s). Write rows one by one, and eagerly close the writer when finishing
 *            each partition and/or bucket.
 *
 * Caller is expected to call `writeWithIterator()` instead of `write()` to write records.
 */
class DynamicPartitionDataConcurrentWriter(

```

A solution, @revans2 please help review:
- Disable `require-single-batch`, and this will solve the OOM problem.
- Then we can add an optimization. Sort each batch and write the multiple splits one by one while keeping the writers open; if opened writers exceed a threshold, `out-of-core` sort the rest batches, and write partitions one by one.  
Only need to keep a `partition-value` to `partition-writer` map.

Other details
- Set the proposed `DynamicPartitionDataConcurrentWriter` like writer as default? 
   Spark does not set it as default.
```
        // maxConcurrentOutputFileWriters default value is 0.
        val maxWriters = sparkSession.sessionState.conf.maxConcurrentOutputFileWriters
        val concurrentWritersEnabled = maxWriters > 0 && sortColumns.isEmpty
```

**Comment by jlowe** [comment]
> Sort each batch and write the multiple splits one by one while keeping the writers open

One significant issue with this approach is that if the cardinality of keys within a batch is high, the number of rows written to a row group will be vanishingly small, increasing the size of the resulting output file and reducing the efficiency of subsequent reads from the file.  Unlike the CPU writers which buffer the inputs as they are written, the GPU writers can only write entire row groups/stripes for each write call, so we would need to do the buffering on our end to prevent this undesired behavior.  Caching insufficiently large batches for keys while waiting for new batches will have its own ramifications, of course.

> Set the proposed DynamicPartitionDataConcurrentWriter like writer as default?

I don't think this is a good idea.  As mentioned above, each writer held open will add significant memory pressure on the executor since it needs to cache a significant amount of data to achieve efficient encodings in the output file.  We either need to honor the configuration setup in Spark and act accordingly, or provide separate configs to handle this.  The user needs the ability to control how this behaves to control both the amount of memory pressure in the executor and the client load on the distributed filesystem.

**Comment by revans2** [comment]
Okay I chatted with @jlowe about this and I don't think there is a single solution that is always a clear winner.

So I would propose that we complete this issue by just doing the out of core sort. Get that working, solve the OOM issue and then we can file some follow on issue to explore support for something like DynamicPartitionDataConcurrentWriter.  But the complexity of doing that solution is quite large and unless we have some baseline to compare it to, we will not know if it is faster or not, and in which cases to be able to help us figure out the ideal heuristics/algorithms to do this.
