### ISSUE TITLE
[BUG] Job failed when parsing "java.lang.reflect.InvocationTargetException: org.apache.spark.sql.catalyst.parser.ParseException:" 

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5670]
I tried to rewrite the Mortgage ETL using a single raw CSV file downloaded directly from the https://capitalmarkets.fanniemae.com/credit-risk-transfer/single-family-credit-risk-transfer/fannie-mae-single-family-loan-performance-data website.

I can make CPU spark work, however when running in GPU mode, it failed when parsing:
```
Caused by: java.lang.reflect.InvocationTargetException: org.apache.spark.sql.catalyst.parser.ParseException:
```

Complete steps and error stacktrace is in https://github.com/viadea/spark-rapids-examples/blob/new_mortgage_etl/examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-ETL-new.ipynb .

The input data is a single CSV file : 2000Q1.csv

**Comment by nvliyuan** [comment]
I just verified that the issue is specific to spark3.2.* version.
it works well with:
spark3.1.2  +  v2206-SNAPSHOT
spark3.1.2  +  v2204-GA
it failed with:
spark3.2.0 +  v2204-GA
spark3.2.0  + v2206-SNAPSHOT
The issue should be raised because UTC time data, because if I don't add config
```
  --conf spark.driver.extraJavaOptions=\"-ea -Duser.timezone=UTC\" \
  --conf spark.executor.extraJavaOptions=\"-ea -Duser.timezone=UTC\" \
```
GetTimestamp would fallback to cpu which would not raise issue
```
!Expression <GetTimestamp> gettimestamp(first_pay_date#1686, MMyyyy, TimestampType, Some(Asia/Shanghai), false) cannot run on GPU because Only UTC zone id is supported. Actual zone id: Asia/Shanghai; expression GetTimestamp gettimestamp(first_pay_date#1686, MMyyyy, TimestampType, Some(Asia/Shanghai), false) produces an unsupported type TimestampType
```

**Comment by jlowe** [comment]
I was not able to reproduce this unless I also set `spark.rapids.sql.incompatibleDateFormats.enabled=true`

**Comment by viadea** [comment]
Yes the reason why we need to enable `spark.rapids.sql.incompatibleDateFormats.enabled=true` is because the raw CSV data has the format as "MMyyyy" otherwise it falls back to CPU:
```
                !Expression <GetTimestamp> gettimestamp(monthly_reporting_period#2, MMyyyy, TimestampType, Some(UTC), false) cannot run on GPU because CORRECTED format 'MMyyyy' on the GPU is not guaranteed to produce the same results as Spark on CPU. Set spark.rapids.sql.incompatibleDateFormats.enabled=true to force onto GPU.
```

**Comment by jlowe** [comment]
The parse error occurs because during plan canonicalization we end up trying to access a canoncialized Alias which will end up trying to do a parse if it is not resolved.  It's _supposed_ to be resolved, but it thinks it isn't because the child expression of the Alias involves a GpuCast which will not report it is resolved if it involves a timestamp cast and the time zone ID is missing.

It seems like a performance bug that we're trying to access this canonicalized Alias, as it occurs because GpuFilterExec is trying to evaluate items not needed for comparing canonicalized plans.  For example, this patch allows the query to work:
```
diff --git a/sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala b/sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
index adf2ab6b6..7b022811a 100644
--- a/sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
+++ b/sql-plugin/src/main/scala/com/nvidia/spark/rapids/basicPhysicalOperators.scala
@@ -320,7 +320,7 @@ case class GpuFilterExec(
     OP_TIME -> createNanoTimingMetric(MODERATE_LEVEL, DESCRIPTION_OP_TIME))
 
   // Split out all the IsNotNulls from condition.
-  private val (notNullPreds, _) = splitConjunctivePredicates(condition).partition {
+  private lazy val (notNullPreds, _) = splitConjunctivePredicates(condition).partition {
     case GpuIsNotNull(a) => isNullIntolerant(a) && a.references.subsetOf(child.outputSet)
     case _ => false
   }
@@ -332,7 +332,7 @@ case class GpuFilterExec(
   }
 
   // The columns that will filtered out by `IsNotNull` could be considered as not nullable.
-  private val notNullAttributes = notNullPreds.flatMap(_.references).distinct.map(_.exprId)
+  private lazy val notNullAttributes = notNullPreds.flatMap(_.references).distinct.map(_.exprId)
 
   override def output: Seq[Attribute] = {
     child.output.map { a =>
```

However I think this is ultimately patching a symptom rather than the root cause.  The CPU FilterExec code is also not being lazy in its FilterExec construction, but it does not crash with the parse error since it's Cast expression has the necessary timezone ID specified to consider itself resolved.

Ultimately we need to figure out why the timezone ID is not being specified (it's either missing or being lost during canonicalization).
