### ISSUE TITLE
[FEA] Auto-merge between branches

### ISSUE THREAD

**Issue by sameerz** [NVIDIA/spark-rapids#579]
As we close our 0.2 branch and open a 0.3 branch, there will be a time period when 0.2 is the default branch, but we will want all changes in 0.2 to be auto-merged to 0.3.  

This request is to create a webhook to notify of successful merges on the default branch, duplicate the PR and merge to the new branch version.  The merge should succeed if there are no conflicts.  If there are conflicts that require human evaluation, the merge should fail and note that human intervention is required.  

An example of this in another repository is https://github.com/rapidsai/cudf/pull/6006 

https://github.com/rapidsai/cudf/pull/6006

**Comment by pxLi** [comment]
Hi, I just submitted https://github.com/NVIDIA/spark-rapids/pull/582 to support this feature. And I choose to use `github actions` instead of cudf's jenkins workflow, since it is easy for us to setup and maintain.

NOTE: There are some limitation here to achieve the auto-merge feature: We should not add blocking rules to BASE branch aka `branch-0.3` here.

Some demo run on my fork:
1. [job: auto-merged](https://github.com/pxLi/spark-rapids/runs/1001446014), [PR link](https://github.com/pxLi/spark-rapids/pull/25)
2. [job: merge conflict](https://github.com/pxLi/spark-rapids/runs/1001499224), [auto-merge PR link](https://github.com/pxLi/spark-rapids/pull/28), [conflict fix PR link](https://github.com/pxLi/spark-rapids/pull/29)
3. [job: no commits](https://github.com/pxLi/spark-rapids/runs/1001651908)

@sameerz  who will be responsible for creating that `branch-0.3`? I can help create one and push it to upstream. cc @jlowe @revans2 

BTW auto-merge script and Dockerfile are located at https://gitlab-master.nvidia.com/peixinl/automerge

**Comment by tgravescs** [comment]
its odd to have auto merge script in different repo, any reason not to just put it in GitHub?
