### ISSUE TITLE
[BUG] When using Alluxio+Spark RAPIDS, if the S3 bucket is not mounted, then query will return nothing

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5892]
Say I have a S3 bucket named "s3://abc" and I did not mount it on Alluxio.

Then if I set:
```
set spark.rapids.alluxio.pathsToReplace=s3://abc->alluxio://master_ip:19998/abc
```

The query on s3://abc will return nothing.
I think we need to fix this by returning a meaningful error message.

**Comment by GaryShen2008** [comment]
Alluxio has REST API to query the mountPoint info from the masterhost:19999. https://docs.alluxio.io/os/restdoc/stable/master/index.html
We are able to check if the path is mounted or not.

**Comment by GaryShen2008** [comment]
Need to check what returned from Alluxio reader when reading an unmounted directory.
If we can't recognize the unmounted directory, we'll have to talk to Alluxio for help.

We can't use REST API because the port 19999 is configurable, we don't know what it is from spark.rapids.alluxio.pathsToReplace.

**Comment by GaryShen2008** [comment]
There's a log like "WARN InMemoryFileIndex: The directory alluxio://**:19998/** was not found. Was it deleted very recently?". The FileNotFoundException has been captured in Spark.
I think it's because we still get meta from s3 bucket, then replace the path.
If we can replace the path earlier as we use alluxio path directly, the spark job will fail by "AnalysisException: Path does not exist".

**Comment by wbo4958** [comment]
Seems we can't hack this at a very early phase, AKA (read the file and infer schema). in this case, can we fall back to reading s3 instead of the alluxio way?

**Comment by GaryShen2008** [comment]
As a short-term solution, I checked the folder existence in Alluxio. If the folder is not there, we return the FileNotFound exception instead of empty result.
