### ISSUE TITLE
[FEA] Set default value of spark.task.resource.gpu.amount to 1/spark.executor.cores

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#5992]
I wish we can set the default value of spark.task.resource.gpu.amount to 1/spark.executor.cores so that users do not need to manually set it.

**Comment by nvliyuan** [comment]
@viadea since in some cases of XGBoost demo, we need to set spark.task.resource.gpu.amount=1

**Comment by viadea** [comment]
> @viadea since in some cases of XGBoost demo, we need to set spark.task.resource.gpu.amount=1

I agree. 
The ideal requirement is:
By default, set spark.task.resource.gpu.amount to 1/spark.executor.cores.
In Xgboost training/inference case, dynamically set spark.task.resource.gpu.amount=1.

**Comment by tgravescs** [comment]
the resources are parsed before our DriverPlugin would run so we can't set this just in the plugin.

It doesn't make sense to make this change in Spark because this is very much a Rapids plugin specific setting, someting like ML wouldn't use this setting because it would normally run 1 task per GPU.

I don't know any other way to set this by default so closing
