### ISSUE TITLE
Improve Spark version selection in premerge tests

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids#6043]
It looks like when we add a new patch version, we always leave the first patch version such as 3.1.1, 3.2.0 as the one on which the tests are run. I think we should rather always move the tests forward to the latest patch version, i.e. 3.1.3 and 3.2.2 to add value

In addition I think the intention of the comment on L41 is that we run tests in premerge for one patch version per feature version. Thus 330 should not skipTests.

_Originally posted by @gerashegalov in https://github.com/NVIDIA/spark-rapids/pull/6031#discussion_r926255931_

**Comment by pxLi** [comment]
> I think we should rather always move the tests forward to the latest patch version, i.e. 3.1.3 and 3.2.2 to add value

Since we cover UTs of all shims in nightly test. 
For the strategy of picking shims tests in pre-merge (should not take so long but would cover more cases), 
I would like to hear more opinions for this one. cc @tgravescs @jlowe @revans2 @sameerz @GaryShen2008 

> Thus 330 should not skipTests.

Currently when adding/modifying shims, 
people may not be able to adjust the corresponding test params well in premerge script.
We can ask code reviewer to pay more attention to it, and also we could have a place to define the list of 
shims-run-UTs
shims-not-run-UTs
in premerge CI

**Comment by tgravescs** [comment]
I think 330 tests got disabled when it was having issues and blocking premerge and then we forgot to turn it back on, so we should reenable these.  As far as which version we run I'm fine with running on the latest released patched release, I don't see big difference in those, the idea was sanity test that you covered that shim, though its not always true that all maintenance versions have the same shim.   I would not be in favor of running only on the snapshot version since those are not necessarily going to be released in that version of spark rapids plugin and can be much less stable.

**Comment by gerashegalov** [comment]
> I don't see big difference in those, the idea was sanity test that you covered that shim, though its not always true that all maintenance versions have the same shim

my rationale is that the prior patch release has been tested for months at the point we are adding the new one. So if we can't run shims to keep premerge on a quicker side, the probability to discover issues is higher with the new Spark version.

**Comment by tgravescs** [comment]
Perhaps, but in either case its a released Spark version and presumably we have run the tests against it for a while, so the main thing we are looking for are changes to our code that wouldn't work with a Spark version.... and going with the rationale that we are trying to make sure you shimmed our code properly, I don't see that it matters.

**Comment by GaryShen2008** [comment]
Hi @gerashegalov , it's one issue long time ago. Is it still a problem for us to solve?

**Comment by gerashegalov** [comment]
@GaryShen2008 two co-workers  disagreed with me that it was something to solve even when I opened the issue. 

The situation as is and this suggestion have the same drawback that we don't test all shims we support.

As a compromise given the still-existing resource constrains let me pitch a compromise: 
for each [[MAJOR].[FEATURE]](https://spark.apache.org/versioning-policy.html) pick a random MAINTENANCE

**Comment by gerashegalov** [comment]
no responses, closing
