### ISSUE TITLE
Find a better way to update the Alluxio paths automatically

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#6070]
This is a follow-up of https://github.com/NVIDIA/spark-rapids/pull/6048. 

In the PR above, the Spark code of [inferPartitioning](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/PartitioningAwareFileIndex.scala#L171) are fully ported to plugin side whose only purpose is to construct a `PartitionSpec` with new replaced file paths.

This is an expensive way that involves many unnecessary calculations. We should reconsider the "re-building path" process and find a proper way to deal with all Spark versions.

**Comment by tgravescs** [comment]
Also note that the fix for https://github.com/NVIDIA/spark-rapids/issues/6029 is going to handle that specific case and others if we know the FileIndex type but the issue could still happen if we don't know the type and it falls back to the existing inferring code.  We could modify spark to handle the BooleanType or we could do this issue and find a different way.
