### ISSUE TITLE
[BUG] withPsNote on ArrayMin does not appear in generated docs

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#6330]
The `ArrayMin` expression has a `withPsNote` annotation, but this annotation does not appear in the generated documentation at https://github.com/NVIDIA/spark-rapids/blob/branch-22.10/docs/supported_ops.md.

**Comment by HaoYang670** [comment]
I guess the bug is that we add `PsNote` on `FloatType` and `DoubleType`, but `ArrayMin` only supports ArrayType.

We should add the PsNote to `ArrayType(FloatType)` and `ArrayType(DoubleType)` I guess. But it seems like the `TypeEnum` doesn't have a constructor  for nested types.

**Comment by revans2** [comment]
> We should add the PsNote for `ArrayType(FloatType)` and `ArrayType(DoubleType)` I guess. But it seems like the `TypeEnum` doesn't have a constructor for nested types.

In those cases we usually just add a single PS not for ArrayType explaining that it has issue with floats and doubles

**Comment by revans2** [comment]
Talking to @jlowe I think we probably also want to add in an error so that if we add a psNote to a type that Spark does not support, that we throw an exception when generating the docs.  We might want to go even further and throw an exception for any type that we say we support, but Spark says it does not.

**Comment by HaoYang670** [comment]
After removing the `hasNan` config from `GpuArrayMin`(#6317), we can close this issue without fixing it.
