### ISSUE TITLE
[BUG] Questions about `spark.rapids.memory.uvm.enabled`

### ISSUE THREAD

**Issue by JustPlay** [NVIDIA/spark-rapids#634]
**What is your question?**
For `spark.rapids.memory.uvm.enabled`
1.  does this feature really work? (in tpc-ds query13, i turn this switch on, but still OOM)
2. I want to known (a) how does this feature works，(b) what kind of host memory does it use (pined or pageable), (c) how much host memory will it use, (d) how much is it's  impact on performance

**Comment by sameerz** [comment]
Hi, `spark.rapids.memory.uvm.enabled` is an experimental feature, and one which is not well tested as noted in the configs documentation at https://nvidia.github.io/spark-rapids/docs/configs.html .  It is not one that has been prioritized for testing.  

This feature would need to be recognized by RMM so it allocates beyond the GPU available memory limit in order to really be effective.  

This should probably a bug where UVM cannot use more than GPU memory.

**Comment by abellina** [comment]
One issue is the configuration. Currently our configuration is a fraction of the pool, and it is a percentage. We could allow the percentage to go above 100% to allow the user to describe over-subscription, both in the initial sense and maximum (e.g. "give me 200% memory to begin with, but don't go above 250%"). Not sure if this clear to everyone.

The other issue is that as you said, we haven't really tested with UVM. I ran a test lately and I see other issues, like illegal accesses when UVM is turned on, and also slowness in some configurations. So I would not depend on this setting, and I wonder if we should remove it.

**Comment by jlowe** [comment]
> I wonder if we should remove it.

Agreed.  The bug is resolved either by removing the config from the public documentation since we're not really testing it, or we resolve it by fixing the functionality and start at least smoke-testing it.  If the latter, the first step is to allow the initial and max GPU pool fraction settings to go above 1 _if and only if_ the UVM config is enabled, and make sure the RMM pool resource will successfully initialize and actually try to allocate beyond normal GPU limits with settings above 1.

**Comment by JustPlay** [comment]
> We could allow the percentage to go above 100% to allow the user to describe over-subscription, both in the initial sense and maximum (e.g. "give me 200% memory to begin with, but don't go above 250%")

> If the latter, the first step is to allow the initial and max GPU pool fraction settings to go above 1 _if and only if_ the UVM config is enabled

Sorry, i did not know this setting method, i still use a percentage 0.9; 





> and make sure the RMM pool resource will successfully initialize and actually try to allocate beyond normal GPU limits with settings above 1

I had not seen some code in the rapids/rmm  related to this feature, does rapids/rmm support it for now?

**Comment by jlowe** [comment]
> does rapidsai/rmm support it for now?

I'm not sure RMM explicitly supports and tests with it, but it doesn't explicitly preclude it.  I don't believe RMM has to know CUDA managed memory is being allocated, as it's just acting as a pool allocator.  It takes large blocks from the underlying allocator and carves up those blocks to serve up allocations.  It shouldn't need to know whether those blocks are device memory or managed memory, as it doesn't make any assumptions that the CPU can directly touch the address spaces from the underlying allocator.

**Comment by abellina** [comment]
So in my experiments if our settings _would_ allow the above 100%, I was able to get an RMM pool instantiated with 64GB on a 32GB device. So yeah UVM just satisfied that allocation RMM made.

I was able to use this pool as well to some success. In queries where we would detect RMM OOM, we wouldn't. But I ran into odd issues like the ones I mentioned earlier. So it goes back to the support/test.

**Comment by JustPlay** [comment]
> I don't believe RMM has to know CUDA managed memory is being allocated

@jlowe  does UVM only support cuda managed memory(cudaMallocManaged, cudaFree), not the cuda memory(cudaMalloc, cudaFree) ?

**Comment by abellina** [comment]
@JustPlay it supports both:

1.`managed_memory_resource`: https://github.com/rapidsai/rmm/blob/branch-0.16/include/rmm/mr/device/managed_memory_resource.hpp#L65
2. `cuda_memory_resource`: https://github.com/rapidsai/rmm/blob/branch-0.16/include/rmm/mr/device/cuda_memory_resource.hpp

RMM is built to be pluggable so we compose a memory resource pipeline in our code to satisfy user driven settings, as passed to the rapids plugin:

https://github.com/rapidsai/cudf/blob/branch-0.16/java/src/main/native/src/RmmJni.cpp#L353

**Comment by revans2** [comment]
@jlowe @abellina @tgravescs @sameerz We need to make a decision on what we want to do with UVM support.  I can see it being very useful in cases where we almost run out of memory, but it can also be problematic for UCX unless we allocate bounce buffers outside of RMM explicitly. I can see us really wanting it for some more experimental cases like #640 

So are we going to support UVM for the 0.2 release?  Are we going to try and support it for the 0.3 release or beyond? 

If we are never going to support it we should remove the config totally.
If we see us wanting to support it later on then we should mark the config as internal for now.
If we want to support it for 0.3 then we need to come up with a plan for testing it and fixing/documenting any issues we run into so that we can say that we truly support it.

**Comment by jlowe** [comment]
I don't think we have enough time to add full support for this feature in the 0.2 timeframe.  We're on the verge of the 0.2 release burndown.

IMO we should try to support it at some point, and the 0.3 release would be a good target.  So my vote is to mark the config internal for now to reduce confusion in the 0.2 release.

**Comment by revans2** [comment]
> IMO we should try to support it at some point, and the 0.3 release would be a good target. So my vote is to mark the config internal for now to reduce confusion in the 0.2 release.

That is what I am leaning towards, but I would like to hear from @sameerz to be sure that he agrees.

**Comment by sameerz** [comment]
Agreed, I think this is a feature we should continue to test and try out before we say we will never support it.  We are too close to 0.2 to make any fixes.  At this point we should mark the `spark.rapids.memory.uvm.enabled` config as internal to avoid confusion.

**Comment by jlowe** [comment]
I'll put up a PR shortly to make the config internal.
