### ISSUE TITLE
[QST]GPU and CPU memory allocation

### ISSUE THREAD

**Issue by lw-cxn** [NVIDIA/spark-rapids#6620]
**What is your question?**
I want to ask whether the raw data read is stored in CPU memory or GPU video memory? And where are the intermediate results of GPU calculation stored? Exchange via shared memory? If all operators are executed on the GPU, assuming that video memory can store all data, do you still need to use CPU memory?

**Comment by lw-cxn** [comment]
Okay, thanks for your reply. A data structure of the Table type is constructed when the host (CPU) memory is transferred to the device (GPU) video memory, as shown in the following figure.
Table{
	columns=[ColumnVector{
		rows=1,
		type=STRING,
		nullCount=Optional.empty,
		offHeap=(ID: 1017fc576bc87d0)
	},
	ColumnVector{
		rows=1,
		type=STRING,
		nullCount=Optional.empty,
		offHeap=(ID: 1027fc575543a00)
	}],
	cudfTable=140486077350896,
	rows=1
}
The batch operation of the GPU operator is the columns above. The offHeap indicates the out-of-heap memory. Does the CUDF copy the offHeap data to the device (GPU) video memory? But I didn't see it.

In addition, if the data calculated by the GPU operator is still calculated on the GPU, will the data in the video memory be directly used instead of being transmitted to the CPU? The data is copied to the CPU only when a rollback operation is performed?

During data transmission, is it considered to copy only the data of the calculation part? If the data is not involved in the calculation, do not copy the data by adding indexes?

For example:select a, b from table where a != 0
If the filter needs to be rolled back, can I copy only the data in column a to the CPU? After the CPU calculates the data, the CPU returns the data and reassembles the data?

**Comment by revans2** [comment]
Sorry this gets a little complicated. Most of the complexity is due to memory management and trying to make something like java which relies on garbage collection play nicely with C++/CUDA that have explicit memory management.

There are a number of object that hold some memory `offHeap`. This could be a memory buffer as is the case in [HostMemoryBuffer](https://github.com/rapidsai/cudf/blob/branch-22.10/java/src/main/java/ai/rapids/cudf/HostMemoryBuffer.java) or it could be a pointer to a C++ class instance as is the case for something like [Scalar](https://github.com/rapidsai/cudf/blob/branch-22.10/java/src/main/java/ai/rapids/cudf/Scalar.java), or it could be a combination of them which is what happens with ColumnVector and Table. The C++ class instances may point to other resources too like GPU memory. But it is up to the C++ class to handle cleaning that all up properly.  This is why we call it `offHeap`, even if what it is pointing to is mostly related to GPU memory.

Internally in java for most of these java objects we are doing reference counting. So when you add a `ColumnVector` to a `Table` the `Table` will increment the reference count on that `ColumnVector` so it is not released until the `Table` is also closed. This lets us create a `ColumnVector` and treat it a lot more like a regular java object.  We can pass it around. We can add it to other objects. We just have to be sure that there are clear rules about when to decrement the reference count and when to increment it.  It is not perfect but generally it works okay. When it does not work well, then we want ways to debug this and also let the garbage collector clean up after us. To do this we separate out the parts that need to be tracked for debugging/cleanup into a separate hidden class from the public facing class.  We register it with a [MemoryCleaner](https://github.com/rapidsai/cudf/blob/branch-22.10/java/src/main/java/ai/rapids/cudf/MemoryCleaner.java) that will let us query what is outstanding. Keep track of when and where a reference count was changed, and also lets something similar to a finalize run that will clean up the off heap parts if the garbage collector got to it before we could free the resources through the proper means, and we can output error messages when this happens.

Generally speaking a `HostColumnVector` will store its data in CPU memory off heap. a regular `ColumnVector` will store its data in GPU memory, but will have some small amount of CPU memory to store metadata about it. A `Table` cannot point ot a `HostColumnVector` only to data on the GPU.

Now for an example like
```
select a, b from table where a != 0
```

If we assume that table is a set of parquet files stored in HDFS.  Spark on the CPU will get the list of files to scan. It will pass that information on to the rapids plugin along with the list of columns to read `a` and `b` and the predicate `a != 0`.  The rapids plugin will then translate that information into a set of tasks that will run on Spark, but use the GPU and CPU to do the processing. First the tasks will get a set of files and splits to read the data from. They will read the parquet footer for the files that they care about and determine the set of row groups within those files that should be read.  This would be based off of how the files are split up and if the predicate `a != 0` would make it so no data in that row group would be read.  After that the data associated with the row groups in the file we care about and the column are read into CPU memory.  That memory is passed on to CUDF as a HsotMemoryBuffer.  CUDF will then parse the parquet data out of it and turn it into a `Table` that is returned.  The data will be on the GPU.  After that the `Table`, or a Spark equivalent of that called a `ColumnarBatch` would be passed onto a `GpuFilterExec` operation that would run the `a != 0` expressions on the GPU to get a boolean mask, and then a new `Table` would be created with the filtered results. The boolean predicate column and the original input table would then be closed and the GPU memory that they point to would be released.

After that it really depends on what the next operation in the query is. It could be written out to a file in another format. It could be collected back to the CPU for further processing/etc.

I hope that this helps.

**Comment by lw-cxn** [comment]
Well, thank you very much for your reply, which has helped me a lot! 
Another question is, when going back from the GPU to the CPU for execution, do you need to copy all the data on the GPU to the CPU?
