### ISSUE TITLE
[Audit][BUG] Handle updated messageParameters for any thrown Spark exceptions in Spark 3.4.x

### ISSUE THREAD

**Issue by NVnavkumar** [NVIDIA/spark-rapids#6671]
**Describe the bug**
Spark updated the type of `messageParameters` when constructing Spark exceptions from array of strings to a Map with pairs of string. Therefore when the plugin needs to throw Spark exceptions, it needs to be updated to handle the new types in the constructor.

Spark commit - https://github.com/apache/spark/commit/96ed6dc3e3

**Comment by abellina** [comment]
This seems to be an effort started in Spark 3.2.x where Spark is making `AnalysisException` more centralized and context rich (first PR I can find: https://github.com/apache/spark/pull/32850). The file [error-classes.json](https://github.com/apache/spark/blob/master/core/src/main/resources/error/error-classes.json) is the centralized source of truth, where the string messages are getting moved and these classes, and the map passed in `messageParameters` is used to interpolate in values.

Note that this is probably a complex task. We'd need shim work to backport the new way of doing things to old spark's.

**Comment by abellina** [comment]
Please note, related to this issue is: https://github.com/apache/spark/commit/22483167e2, where the `errorSubClass` field was removed from `AnalysisException` and other derived exceptions: https://github.com/apache/spark/commit/22483167e2#diff-bea7865390cbdd74ea3af9b56a0905ea15cd5789ee5d87932aff630a6a2a3ff0L41.
