### ISSUE TITLE
[BUG] Does spark/rapids really has the gpu-aware task scheduling ability？

### ISSUE THREAD

**Issue by JustPlay** [NVIDIA/spark-rapids#678]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5866501/92433678-546ad300-f1d0-11ea-9b11-08a140642b51.png)

the pic above shows a reduce stage, we have 13-machine, each machine has a T4, so we have 13 executors total, one executor per gpu, and each executor has 24 cpu cores

we have set the shuffle partition = 13, and there really exists 13 tasks to handle those partitions, but why the tasks are not equally distributed to each executor，some machines/executors are idle, but others are overload，and thus hart the performance

**Expected behavior**
I want the tasks (or data need to be processed) to be equally distributed to each executor， so no long-tail

**Comment by tgravescs** [comment]
this is a spark scheduling question not a spark-rapids plugin question.
I'm assuming you are allowing more then 1 task to run on the GPU? (ie spark.task.resource.gpu.amount=(1/24). If so then spark is doing just fine.

More than likely the reason is locality. Spark uses locality to decide where to put thing where it thinks is most efficient. Meaning the most data is local on that node so you don't have to transfer as much over the network. 

We were actually doing a little experimenting with adding an option to spark to force it to spread, but in that particular case the performance was the same or worse. You may get some efficiencies in spreading them by having more resources there but at the same time you likely have to transfer more data over the network.

Do you know that the tasks being put an a single executor caused a long tail?  Perhaps you have the spark.rapids.sql.concurrentGpuTasks < 7 so they couldn't really run on GPU at once?  Note that spark.rapids.sql.concurrentGpuTasks is a plugin config and it not directly tied into how spark schedules executors.

**Comment by revans2** [comment]
@tgravescs  Please correct me if I am wrong, but I think we did the spread experiments before we introduced the GPU Semaphore, and it might be nice to see if it is still the case now.

**Comment by tgravescs** [comment]
we did this test last week, the semaphore was there but I think in this case it was set to the like 2 or 4 and we were only getting 2 tasks per executor so both were still allowed to run.  
The semaphore setting is why I asked what it was set to here to see if they are getting more tasks then can run concurrently.  If that is the case it would more than likely be beneficial to spread them, we could potentially do an experiment to replicate similar setup.

**Comment by tgravescs** [comment]
Note one thing you may try is setting spark.shuffle.reduceLocality.enabled=false

**Comment by abellina** [comment]
One issue you may run into is that spreading compute will also mean increasing network transfers, especially when turning off locality. But, if there are fast links between executors (e.g. NVLink for example or even PCIe, and high BW network), I could see that being less of an issue. I also saw this on benchmarks I was using, and we are aware of the issue, but still need to formulate what the best path forward is.

**Comment by jlowe** [comment]
@JustPlay are you running with `spark.locality.wait=0s`?  I have seen Spark often schedule all of the tasks on just a few executors in subsequent stages without that setting.

**Comment by JustPlay** [comment]
> @JustPlay are you running with `spark.locality.wait=0s`? I have seen Spark often schedule all of the tasks on just a few executors in subsequent stages without that setting.

yes

**Comment by tgravescs** [comment]
@JustPlay  did you have a chance to try spark.shuffle.reduceLocality.enabled=false ?
