### ISSUE TITLE
[QST] How can I limit the rows of spark df transfered from cpu to gpu to avoid gpu memory overflow.

### ISSUE THREAD

**Issue by mtsol** [NVIDIA/spark-rapids#6945]
I see this flag spark.rapids.sql.exec.CollectLimitExec but this reduces the spark df to single partition as per documentation. Kindly suggest any other way to doing that

**Comment by tgravescs** [comment]
there is potentially multiple ways of doing this depending on which spark exec is having issues.  You can see our tuning guide which goes over most of them:
https://nvidia.github.io/spark-rapids/docs/tuning-guide.html

Essentially you want to control the amount of data read or the batch size configurations.  The specific sections I recommend taking a look at:
https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#shuffle-partitions
https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#input-files
https://nvidia.github.io/spark-rapids/docs/tuning-guide.html#columnar-batch-size

the flag spark.rapids.sql.exec.CollectLimitExec is not meant to limit amount of data, that is to turn on the CollectLimitExec to run on the GPU. This happens you do something like df.collect(), but its off by default because we haven't seen benefit from running this on the GPU.

If those don't answer your question please give us more information about exactly where you are getting a GPU oom. The stack trace would be very useful.

**Comment by mtsol** [comment]
How can I specify only these spark stages are shifted to GPU for computation and not the other ones to reduction the data shifting cost from RAM to GPU memory.

**Comment by jlowe** [comment]
The portions of the plan shifted to the GPU are not on a stage-by-stage basis but rather node-by-node in the SQL execution plan.  Typically nodes will be translated if the node has a compatible GPU version and all sub-expressions can also be translated.  See https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/docs/configs.md#execution for the configs that control the translation of execution nodes and https://github.com/NVIDIA/spark-rapids/blob/branch-23.02/docs/configs.md#expressions for the control of expression types.

If this is not sufficient control, it would help if you could show the SQL plan and describe what specific transformation you want to control for it (i.e.: a before translation plan and a desired after translation plan).
