### ISSUE TITLE
Add 'reduce' alias for ArrayAggregate 

### ISSUE THREAD

**Issue by razajafri** [NVIDIA/spark-rapids#7498]
As part of https://github.com/apache/spark/commit/ccbd9a7b98 Spark added  `reduce` alias for ArrayAggregate (aggregate(array(...)))

We may want to add this support if we want to support Presto DB

**Comment by revans2** [comment]
All this API is doing is providing an alias for existing functionality. It means that you can call ```SELECT reduce(array(1, 2, 3), 0, (acc, x) -> acc + x);``` and spark SQL will treat it exactly the same as calling ```SELECT aggregate(array(1, 2, 3), 0, (acc, x) -> acc + x);```. There is no change needed on our part to get this functionality. That said we do not support `ArrayAggregate` currently because of how it is implemented using a higher order function. There is no simple way to translate these higher order functions into something that we can run. When we have a customer that needs this type of functionality we can look into what we can do to support them in this.
