### ISSUE TITLE
[BUG] Investigate high task deserialization

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#773]
**Describe the bug**
A user question in #697 reported high task deserialization metrics when using the plugin.  We need to investigate why using the plugin caused much higher task serialization overhead than the normal CPU query.

**Steps/Code to reproduce bug**
Execute TPCx-BB queries and examine task deserialization metrics.

**Expected behavior**
Task deserialization metrics should not be significantly higher than the overhead for the equivalent CPU query.

**Comment by tgravescs** [comment]
@YeahNew you reported this in https://github.com/NVIDIA/spark-rapids/issues/697. I'm curious how much difference in task deserialization were you seeing?  Can you point to specific instances (stages and tasks) in the queries you were running?

I was able to see some differences in the final stage for query 21 and 22. The difference was 0.5s on gpu vs 97ms on cpu. The version I'm seeing,  a lot of it came from codegen and it looks like the reason is that the cpu side did code gen in an earlier stage and that first codegen has a high initialization time (a few hundred ms).   When I go back and compare the earlier stages the GPU deserialization time is way lower (72ms on gpu and 0.4s on cpu) for that stage because the cpu side hit the codegen and presumably had to do a bunch of initialization at that poin.

I want to make sure I'm seeing the same thing you were though.

**Comment by tgravescs** [comment]
closing this since no other information and it appears that this is just seeing it during different stages.
