### ISSUE TITLE
[AUDIT] Investigate fix for "bad" output for range window functions with overflowing bounds

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids#7957]
https://issues.apache.org/jira/browse/SPARK-41793 purports to correct bad output for range window functions where the range check might cause overflows.

The example provided in the bug boils down to:
```sql
create table test_table(a long, b decimal(38,2));
insert into test_table 
values
  ('9223372036854775807', '11342371013783243717493546650944543.47'),
  ('9223372036854775807', '999999999999999999999999999999999999.99');

select * from test_table;

select 
  count(1) over(
    partition by a 
    order by b asc
    range between 10.2345 preceding and 6.7890 following) as cnt_1 
  from 
    test_table;
```

Spark 3.4 produces `[1, 0]`, because the second row's comparisons produce overflows. 
All prior Spark versions produce `[1, 1]`.
All other databases that were checked (Hive, SQLite, MySQL, etc.) produce `[1,1]`.

@gerashegalov is closely familiar with this issue.
I (vehemently) disagree with the findings in SPARK-41793, because it is counter-intuitive *not* to count the current row in the window. 

Regardless, we might need to find a way to resolve this discrepancy.

**Comment by gerashegalov** [comment]
Hi @mythrocks,  just double-checking if you found more issues related to  [SPARK-41793](https://issues.apache.org/jira/browse/SPARK-41793?focusedCommentId=17692451&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17692451). Regarding that particular test case as you see from Wenchen's comment, we argued our case successfully, and I removed xfails in #7810. 

Technically the way you wrote it in this issue  `insert into test_table` fails because of an implicit unsafe cast from string which fails even in 3.1.1
 
```
Error in query: Cannot write incompatible data to table '`default`.`test_table`':
- Cannot safely cast 'a': string to bigint
- Cannot safely cast 'b': string to decimal(38,2)
```

if you download the latest rc tarball (3.4.0-rc4) from https://dist.apache.org/repos/dist/dev/spark/v3.4.0-rc4-bin you can see that the our original issue is resolved

```SQL
spark-sql (default)> create or replace temp view test_table
                   > as select * from values
                   >   (9223372036854775807l, cast('11342371013783243717493546650944543.47' as decimal(38,2))),
                   >   (9223372036854775807l, cast('999999999999999999999999999999999999.99' as decimal(38,2)))
                   > as data(a, b);
Time taken: 1.073 seconds
spark-sql (default)> 
                   >   SELECT 
                   >     COUNT(1) OVER (
                   >       PARTITION BY a 
                   >       ORDER BY b ASC 
                   >       RANGE BETWEEN 10.2345 PRECEDING AND 6.7890 FOLLOWING
                   >     ) AS CNT_1 
                   >   FROM 
                   >     test_table;
1
1
Time taken: 1.22 seconds, Fetched 2 row(s)
```

**Comment by mythrocks** [comment]
Ah, no. My mistake. I hadn't realized that we had prevailed there. I'm closing this bug.

Thanks for the correction, @gerashegalov.
