### ISSUE TITLE
[AUDIT][SPARK-38829] Respect new config option `spark.sql.parquet.inferTimestampNTZ.enabled`

### ISSUE THREAD

**Issue by andygrove** [NVIDIA/spark-rapids#8201]
**Is your feature request related to a problem? Please describe.**
Spark 3.5.0 introduced a new config option, `spark.sql.parquet.inferTimestampNTZ.enabled`.

**Describe the solution you'd like**
Respect the config or fall back to CPU.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/apache/spark/commit/ae24327e89

**Comment by NVnavkumar** [comment]
This was actually introduced in Spark 3.4.0. Right now we should respect the config and fallback to CPU because we don't support the TimestampNTZType in Spark.

See https://github.com/NVIDIA/spark-rapids/blob/branch-23.06/sql-plugin/src/main/spark340/scala/com/nvidia/spark/rapids/shims/ParquetTimestampNTZShims.scala

**Comment by NVnavkumar** [comment]
This was handled in #5472. Closing this issue
