### ISSUE TITLE
[BUG] GpuExpression columnarEval can return scalars from subqueries that may be unhandled

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8303]
#8293 is an instance of a case where a subquery caused a sub-expression to be evaluated as a scalar in a context that expected a column vector.  One way to handle it is to explode the scalar out to a full column the same size as the batch and proceed as if it were a column all along (not necessarily the most performant), or update all the code to treat scalars as scalars (which may involve hacking the scalar into a 1-row column since most cudf functions operate on columns not scalars).

If we want to go the "always explode the scalar into a full column" route, then we should make it so `GpuExpression.columnarEval` is incapable of returning a scalar -- e.g.: it will always wrap the real eval with something like GpuExpressionsUtils.columnarEvalToColumn.

**Comment by revans2** [comment]
We cannot/should not force `GpuExpression.columnarEval` to always return a `ColumnVector` without some kind of an escape valve. We at least need a way for `GpuLiteral`, which is a `GpuExpression` to return a `GpuScalar`, or we are going to completely remove all scalars from the code which will also mess up processing that only supports a literal value for a particular input and expects it.

**Comment by jlowe** [comment]
True, we still need the ability to get scalars in some situations.  Does it make sense to have two forms of expression eval, one that expects to resolve to a scalar because it is explicitly expected, and one that forces it to be a columnar vector (e.g.: via columnarEvalToColumn)?  As it is now, we're likely to keep having to fix places that aren't prepared to handle both.

If we don't want two eval forms, then this issue becomes a tracker to audit all the places where subexpressions are evaluated and updating them to handle scalars (and hope we don't add more places that aren't properly dealing with scalars).

**Comment by revans2** [comment]
It is not just sub-expressions. GpuCoalesce can also return a scalar and I think there may be others.  But in general, yes I think what we want is two APIs.  One that is guaranteed to return a `ColumnVector` and another that is not.  We have that today, but it could really be cleaned up.  If you call the API that could return both you have to support it being a `GpuScalar` or a `ColumnVector` no exceptions.  That means we are going to have to update `Gpu{Unary|Binary|Trinary}Expression` so that it is clean to support cases where we don't cover everything. `GpuArrayContains` is one example where we don't cover all situations, but there are lots of them.

This is not going to be a super simple fix.

If you call the one that returns a ColumnVector you just need to handle that case.

**Comment by abellina** [comment]
I am keeping this issue open from the PR because there is follow on work that has to happen as P0:

- We need to make `GpuScalarSubquery` return a scalar only, not a `GpuColumnVector`
- We need to audit all binary/ternary ops that throw from `doColumnar` and likely update them to handle the scalar. This is going to be on a case by case basis and it needs to be done in tandem with `GpuScalarSubquery` (e.g. we may not want to blindly explode a scalar into a column as there may be semantic differences or performance issues)

@jlowe @revans2 please comment if I've missed something.

**Comment by abellina** [comment]
List of binary expressions that throw from a `doColumnar` with a `GpuScalar` argument:

`doColumnar(GpuScalar, GpuColumnVector)`:
- GpuSortArray
- GpuGetMapValue
- GpuArrayContains
- GpuDateFormatClass
- GpuToTimestamp
- GpuFromUnixTime
- GpuFromUTCTimestamp
- GpuRoundBase
- GpuStartsWith
- GpuEndsWith
- GpuContains
- GpuLike
- GpuRLike
- GpuStringInstr

`doColumnar(GpuColumnVector, GpuScalar)`: none

`doColumnar(numRows, GpuScalar, GpuScalar)`: 
- GpuArrayContains

**Comment by abellina** [comment]
GpuTernaryExpressions are all string expressions, and there are less of them.

- GpuStringLocate
- GpuStringReplace
- GpuStringTranslate
- GpuRegExpTernaryBase
- GpuSubstringIndex
- BasePad
