### ISSUE TITLE
Improve fix for `from_json` function for empty data input column

### ISSUE THREAD

**Issue by cindyyuanjiang** [NVIDIA/spark-rapids#8542]
`from_json` function fails when the input column contains all empty or null strings. Current fix https://github.com/NVIDIA/spark-rapids/pull/8526 is inefficient in terms of GPU memory usage.

This follow-up issue tracks:

- [ ] Improve fix for `from_json` function for empty data input column w.r.t. GPU memory usage
- [ ] Revert current workaround for `strip`, `rstrip`, and `lstrip` once fix https://github.com/rapidsai/cudf/pull/13533 gets merged

**Comment by revans2** [comment]
Actually I don't think we want to revert the change for strip, rstrip, and lstrip. It is likely still a performance/memory win, but very very small.

What I wanted to see what a fix for the empty string replacement in `from_json` The current JSON parser acts differently from all of the other parsers in that it does not return the requested columns. It returns all of the columns it saw, and only uses the types passed in to match it up with the columns it saw. https://github.com/rapidsai/cudf/issues/13473 describes this.

Prior to https://github.com/NVIDIA/spark-rapids/pull/8526 we would replace empty strings with `{}` so that the lines in from_json would not be stripped out.  But #8526 changed it to include an entry for each column. That works, but it is not memory efficient.  We added in https://github.com/rapidsai/cudf/pull/13477 to CUDF to work around most of the issues, so we could stick with `{}` as the replacement so long as there is at least one column in one row in the batch.  But that is hard to detect do we really should just replace the empty columns with something, ideally something that is in the input schema

```
constructEmptyRow(schema: DataType): String = schema match {
  case struct: StructType =>
    if (struct.fields.length <= 0) {
      // This needs to be fixed at a higher level and we want to test for it. The output would be a batch of only rows, no columns
      // so we should just return that. I suspect Spark on the CPU will have issues with this too? but who knows...
      throw new IllegalArgumentException()
    } else {
      s"\"${escapeFieldName(struct.head.name)}\":null"
    }
  case other =>
    throw new IllegalArgumentException(s"other is not supported as a top level type")
}
```

This way the replacement string data is small and we should get the results that we want.
