### ISSUE TITLE
[FEA]UDF compiler plugin is able to compile arbitrary function call in UDF body

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids#855]
**Is your feature request related to a problem? Please describe.**
The udf compiler plugin doesn't support arbitrary function call inside the udf body. When call an external function inside the UDF, an exception of `Unsupported instruction: 182` (182 points to the the Opcode `INVOKEVIRTUAL` in JVM) will be thrown.

**Comment by revans2** [comment]
Just to be clear replacing this with an operator like `CallMethodViaReflection` (`java_method`, or `reflect`) is not an acceptable solution because we will not be able to accelerate the new call with the GPU.

If there really is no other choice, then we may need to look into something like #306 so we can minimize the data transfers to/from the GPU instead.

**Comment by wjxiz1992** [comment]
Here the word "arbitrary" doesn't mean all user-created methods, it's just a call to `external` method. For example, the udf compiler now supports 
```
str.length
```
in the udf body. But it doesn't support compiling the call to a function that contains this `str.length` (#854 ).
I think the main idea to support a recursive search for the final function.

Though user-created methods may be the 90% cases, but we do see the `str.length`  case in a customer's codes.

**Comment by revans2** [comment]
@wjxiz1992 thanks for the clarification.
