### ISSUE TITLE
[QST] /tmp directory filling up

### ISSUE THREAD

**Issue by vivin152** [NVIDIA/spark-rapids#8597]
**/tmp directory filling up**
When using Spark Rapids, i am experiencing the /tmp directory filling up despite setting the local.dir configuration to my other folder
Using rapids-4-spark_2.12-23.04.1-cuda11.jar
and spark version 3.3.0

**Comment by jlowe** [comment]
Thanks for the bug report!  Can you elaborate a bit more on specific file paths are primarily filling up /tmp when using the RAPIDS Accelerator?  Knowing what type of files are appearing there will help us track down what needs to be corrected on our end.

**Comment by vivin152** [comment]
So this is the spark submit command i used:
spark-submit \
--master <URL> \
--driver-memory 10g \
--conf spark.plugins=com.nvidia.spark.SQLPlugin \
--jars rapids-4-spark_2.12-23.04.1.jar \
--conf spark.executer.resource.gpu.discoveryScript=/path/to/spark-3.3.0-bin-hadoop3/spark-3.3.0-bin-hadoop3/examples/src/main/scripts/getGpusResources.sh \
--conf spark.executor.resource.gpu.amount=1 \
--conf spark.executor.cores=6 \
--conf spark.executor.memory=15G \
--conf spark.rapids.sql.concurrentGpuTasks=2 \
--conf spark.rapids.memory.gpu.pooling.enabled=true \
--conf spark.rapids.memory.gpu.pooling.size=13G \
--conf spark.rapids.memory.gpu.allocFraction=0.9 \
--conf spark.rapids.memory.gpu.maxAllocFraction=0.9 \
--conf spark.sql.files.maxPartitionBytes=512m \
**--conf spark.rapids.sql.stableSort.enabled=true \
--conf spark.rapids.shuffle.enabled=true \**
--conf spark.rapids.sql.variableFloatAgg.enabled=true \
--conf spark.rapids.sql.incompatibleOps.enabled=true \
--conf spark.rapids.sql.explain=NOT_ON_GPU \
generate_input.py 

i have set the SPARK_LOCAL_DIRS="/app/vivin/code_tmp" in spark-defaults.conf.sh
but the /tmp directory partition mounted in  linux is getting filled.

**Comment by revans2** [comment]
The only thing I know that we would use /tmp for is the .so's that we extract from the jar to be able to run native code.  Spark/Hadoop do the same thing for some native acceleration, but our .so files tend to be a lot larger.  Like @jlowe said if you could point to specific paths that would help a lot to narrow this down.

**Comment by tgravescs** [comment]
>i have set the SPARK_LOCAL_DIRS="/app/vivin/code_tmp" in spark-defaults.conf.sh

You should not set env variables in the spark-defaults.conf. If you want to set it in spark-defaults.conf set the config **spark.local.dir**.  Side note env variables for spark go into spark-env.sh.

My guess is that isn't being picked up and used properly.  can you verify that the local dirs was picked up properly by Spark?  To into /app/vivin/code_tmp when running and check that Spark created directories there after running an application.  Depending on deploy mode you should see something like spark-ebcd1b45-72dc-4182-ab6d-a12ced32a891.

Also what master are you using,  " --master "  is blank in command above?

**Comment by jlowe** [comment]
If this problem is indeed specific to the RAPIDS Accelerator then my best guess is this is related to the native shared libraries that are dynamically unpacked from the rapids-4-spark_2.12 jar on startup.  These shared libraries are uncompressed into the Java temporary directory (controllable via the java.io.tmpdir property) and then deleted after being opened so the space is always removed even if the JVM crashes.

You could try setting the java.io.tmpdir property to /app/vivin/code_tmp in both the driver and executor Java properties, e.g.:
--conf spark.driver.extraJavaOptions=-Djava.io.tmpdir=/app/vivin/code_tmp
--conf spark.executor.extraJavaOptions=-Djava.io.tmpdir=/app/vivin/code_tmp

Other that the use of the configured Java temporary directory to uncompress the native shared libraries (which are a non-trivial size), I am not aware of any other use of disk space by the RAPIDS Accelerator outside of what is configured for Spark, which @tgravescs covered above.

**Comment by vivin152** [comment]
@tgravescs the above stated  issue got resolved when i used your configurations now the /tmp directory is not getting filled the specified path is getting filled. @tgravescs @revans2  Thank you so much for your time.
