### ISSUE TITLE
[BUG] RapidsShuffleThreadedWriterSuite temp shuffle file test failure

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#8615]
Last night's integration test run failed in RapidsShuffleThreadedWriterSuite:
```
[2023-06-27T08:19:33.353Z] [32mRapidsShuffleThreadedWriterSuite:[0m
[2023-06-27T08:19:34.723Z] [32m- write empty iterator[0m
[2023-06-27T08:19:34.982Z] [32m- write with some empty partitions - transferTo true[0m
[2023-06-27T08:19:35.245Z] [32m- write with some empty partitions - transferTo false[0m
[2023-06-27T08:19:35.506Z] [31m- only generate temp shuffle file for non-empty partition *** FAILED ***[0m
[2023-06-27T08:19:35.506Z] [31m  0 did not equal 3 (RapidsShuffleThreadedWriterSuite.scala:360)[0m
```

**Comment by abellina** [comment]
This is likely a race in the unit test where we are creating and deleting files in the beforeEach/afterEach. I am investingating.

**Comment by abellina** [comment]
Here is a summary of what is going on, and there are several places for race conditions:

1. In this test, the number of writer tests is set to 2. That means we are using a thread pool to write.
2. The test instantites `DiskBlockObjectWriter` with `syncWrites=false`. `syncWrites=true` causes java to call `.sync()` for each record write, so we are not doing that.
3. The test creates an iterator that produces 2 good partitions, and then a third partition that is mostly OK, except that when it reaches one of the last items (the 99,990th) it will throw a SparkException. This exception is thrown on .next when the threaded writer is trying to schedule tasks onto its thread pool (before it submits the task)
4. The shuffle writer code that would have scheduled a task to write this value instead exists and we call `.abort` on the `ShuffleMapOutputWriter`.
5. We do not wait for futures. There could be futures queued the first and second partition, even the third partition, but we don't wait for them because we had an error on `.next`.

I am going to try to repro this locally, but I think what needs to happen is that we ask the test to wait for the write futures and we want `syncWrites=true`. That way we have at least made our attempts at touching these files. If we can't get something other than NFS for the backing store, I may want to replace the `ShuffleMapOutputWriter` with a mock one so we don't go to the file system at all.

**Comment by abellina** [comment]
I can get this to repro locally if I run the test 100 times:
```
- only generate temp shuffle file for non-empty partition *** FAILED ***
  1 did not equal 3 (RapidsShuffleThreadedWriterSuite.scala:362)
```

I will PR some changes shortly.

**Comment by pxLi** [comment]
> I do see see some issues removing a .nfsX file (as far as I understand). This may or may not be related:
> 
> ```
> java.io.IOException: Failed to delete: /tests/target/spark332/tmp/spark-ac343c6b-b810-42f9-a72f-3f15237f2a86/.nfs0000000090ab5a5100002f26
> ```
> 
> @pxLi FYI it would be good to know if we can get something other than NFS for our temp directory in this environment.

For integration tests, we specify the temp folder to /tmp to avoid using NFS storage e.g. https://github.com/NVIDIA/spark-rapids/blob/branch-23.08/jenkins/spark-tests.sh#L113-L118

It would be nice to also direct the temp folder to some other places in unit tests like any paths /tmp/<blah_date> other than workspace mount point (NFS in CI is mounted to jenkins workspace path as `/home/jenkins/agent/workspace`)
