### ISSUE TITLE
[FEA] AQE and DPP work together in rapids

### ISSUE THREAD

**Issue by JustPlay** [NVIDIA/spark-rapids#863]
**Is your feature request related to a problem? Please describe.**

want DPP and AQE can work together in rapids

@jlowe  @revans2

**Comment by revans2** [comment]
What exactly do you mean/want?  Spark itself limits the use of DPP with AQE.  Are you expecting the plugin to override this functionality that is built into spark? I personally think that if we have a solution for this it should go into spark itself, unless there is some part of running on a CPU that would make it impossible compared to doing it on the GPU.

**Comment by JustPlay** [comment]
> What exactly do you mean/want? Spark itself limits the use of DPP with AQE. Are you expecting the plugin to override this functionality that is built into spark? I personally think that if we have a solution for this it should go into spark itself, unless there is some part of running on a CPU that would make it impossible compared to doing it on the GPU.

@chenrui17 here

**Comment by chenrui17** [comment]
> What exactly do you mean/want? Spark itself limits the use of DPP with AQE. Are you expecting the plugin to override this functionality that is built into spark? I personally think that if we have a solution for this it should go into spark itself, unless there is some part of running on a CPU that would make it impossible compared to doing it on the GPU.

well , in spark3.0 now , DPP and AE can not work together , we want to add a rule of AQE  based [https://github.com/apache/spark/pull/29224/files](url) to make it work together . 
and now I met a question  : i found that GpuBroadCastHashJoinExec , GpuBroadCastExchangeExec , etc is in shims project ,  but I want to modify Plugin.scala ,and it is in sql-plugin ，and  i need call GpuBroadCastHashJoinExec and GpuBroadCastExchangeExec in sql-plugin , but when I add pom dependencies in sql-plugin/pom.xml，it occurs error like this:
![image](https://user-images.githubusercontent.com/33319780/94449319-89ba7d80-01de-11eb-8d47-ec544d920759.png)

what should i do ?

**Comment by chenrui17** [comment]
> > What exactly do you mean/want? Spark itself limits the use of DPP with AQE. Are you expecting the plugin to override this functionality that is built into spark? I personally think that if we have a solution for this it should go into spark itself, unless there is some part of running on a CPU that would make it impossible compared to doing it on the GPU.
> 
> well , in spark3.0 now , DPP and AE can not work together , we want to add a rule of AQE based [https://github.com/apache/spark/pull/29224/files](url) to make it work together .
> and now I met a question : i found that GpuBroadCastHashJoinExec , GpuBroadCastExchangeExec , etc is in shims project , but I want to modify Plugin.scala ,and it is in sql-plugin ，and i need call GpuBroadCastHashJoinExec and GpuBroadCastExchangeExec in sql-plugin , but when I add pom dependencies in sql-plugin/pom.xml，it occurs error like this:
> ![image](https://user-images.githubusercontent.com/33319780/94449319-89ba7d80-01de-11eb-8d47-ec544d920759.png)
> 
> what should i do ?

Error:java: Annotation processing is not supported for module cycles. Please ensure that all modules from cycle [rapids-4-spark-shims-spark300_2.12,rapids-4-spark-shims-spark301_2.12,rapids-4-spark-sql_2.12] are excluded from annotation processing

**Comment by revans2** [comment]
https://github.com/apache/spark/pull/29224 was done to allow AQE to work with the rapids plugin which went into spark 3.0.1 and 3.1.0.

This means that if you use a newer version of the plugin 0.2 + against spark version 3.0.1+ or 3.1.0+ then AQE will work.

What I was referring to is that there are checks inside the AQE code that when it detects that a stage has DPP processing enabled it will not enable AQE for that stage too.

The problem you are running into is how our shim system works. @tgravescs please correct me if I get something wrong.

We have a common core for code that works against all version of spark that we support.  Then we have a separate shim layer for each specific version of spark so we can add operators to the base.  The proper implementation of the shim layer is detected at run time and dynamically loaded.

The base provides an abstract API `SparkShims` that lets the core/base part of the plugin interact with they shims as needed. This allows us to avoid the issue you are running into.  If you need to get access to something that is only in the shim layer (because in this case the join base class changed between releases in an incompatible way) then you would need to go though the abstract API to get access to it.

**Comment by JustPlay** [comment]
> What I was referring to is that there are checks inside the AQE code that when it detects that a stage has DPP processing enabled it will not enable AQE for that stage too.

if we want AQE and DPP to co-work,  does these exists some rapids-specific code need change? @revans2

**Comment by tgravescs** [comment]
those aren't supported together yet in Spark itself - see https://issues.apache.org/jira/browse/SPARK-30186
Generally we wouldn't support it until Spark itself supports it.

**Comment by sameerz** [comment]
Given that Spark does not support AQE and DPP together, I am marking this closed.
