### ISSUE TITLE
[FEA] add more metrics to Eventlogs or Executor logs

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#8770]
When the compression ratio of the file is too high, we may encounter GPU OOM errors after decompressing. 
If we have more logs/metrics of the data size before and after decompression in `gpu reader`, it will help us to track it.
And it will be nice if we similar metrics in `gpu writer`.

**Comment by nvliyuan** [comment]
Is it possible for us to add more metrics like the IO/Computation percentage info in a scan/shuffle stage? 
CC @viadea

**Comment by viadea** [comment]
@nvliyuan @revans2 I created a separate tool feature request https://github.com/NVIDIA/spark-rapids-tools/issues/594 to track the [FEA] Profiling tool prints the % of shuffle vs IO vs compute

**Comment by viadea** [comment]
@nvliyuan @revans2 
How about changing the title of this issue as "Handle OOM issue for highly compressed data"? 
Currently the title seems like adding more information to the logs which i believe is misleading.

**Comment by nvliyuan** [comment]
Hi @viadea , the idea of FEA is to add more info to the logs, not specific to the highly compressed data OOM issue.

**Comment by revans2** [comment]
@viadea sorry it has taken so long to respond I am really behind on email right now :(

@nvlyuan I think that is the reason that @viadea is concerned here. He filed an issue about one specific use case and it is not clear how/if this is going to cover that use case with the new name. 

It sounds like there are two issues here, so please correct me if I get something wrong.  1 to fix OOM on highly compressed data as @viadea suggests.  @viadea do you want that for fixing the underlying problems in parquet and a separate one for ORC? or do you want something where we can detect that this is happening with metrics and use the auto-tuner to try and work around the issue?  I think the fix is what we want instead of trying to work around things after the fact, especially if it is not likely that we will be able to work around it in many cases.

The second issue is to add more metrics to the evenlogs or Executor logs. But that one has me a little concerned because we don't know what those metrics are or what questions we are trying to answer with them.  I think that is the first thing we need/want to do is to have an epic with the list of questions that we want an auto-tuner or profiler to be able to answer. Then we can work on understanding what metrics are currently available and what we need to add in to answer those questions.  Also we need to be aware that Spark holds all of these metrics in memory while the job runs. Adding in too many metrics can cause the job/application to crash.

**Comment by viadea** [comment]
I think the main concern is for this specific feature request, the title is too vague. 
@nvliyuan  what exact metrics do you need to add in case of OOM errors due to highly compressed data?
Such as (throwing random ideas here): how many row groups of parquet have been processed, the avg size of the parquet row groups got scanned,etc.

**Comment by nvliyuan** [comment]
@revans2 @viadea My previous thought was if we can add a metric about the data(maybe all columns) size of each task read in GPU scan, and the data size after decompressed, then we could know the compression of the raw data from the eventlog, we don't need to double-check the table/data file schema info. But if the idea does not make sense, please feel free to close this feature request.

**Comment by revans2** [comment]
We already report the amount of data that was read. That is part of Spark itself and shows up at a task level. If you want something at an individual scan operator level we could look into adding that, but we almost never have more than one scan in a task.

The decompressed size is something we could definitely add. But is this just to get the compression ratio?  That would only work after we succeeded in getting the data, and we can get a really rough idea of how bit the output data is based off of the number of output batches from the operator. Not that this is not a good idea, I am just trying to understand it better and what we want to do with the data.

**Comment by nvliyuan** [comment]
since we can estimate the compression ratio from the eventlog, close this issue
