### ISSUE TITLE
[FEA] Support to_json function

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids#8780]
I wish we can support the function to_json.
For example:
```
from pyspark.sql.functions import struct, to_json
data = [("John", "Doe", 21), ("Jane", "Doe", 25), ("Sam", "Smith", 30)]
df = spark.createDataFrame(data, ["first_name", "last_name", "age"])
df = df.withColumn("person", struct("first_name", "last_name", "age"))
df = df.withColumn("person_json", to_json("person"))
df.show()
```

Not-Supported-messages:
```
 ! <StructsToJson> to_json(struct(first_name, first_name#0, last_name, last_name#1, age, age#2L), Some(UTC)) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.StructsToJson
```

**Comment by revans2** [comment]
This is fairly close to being able to write out JSON to a file in the JSON lines format.  We might want to try supporting both because the only real difference is going to be inserting in a \n between the lines at the end and writing it to a file.

First off are there any non-default JSON options that we need to support?
  * ignoreNullFields
  * locale
  * dateFormat
  * timestampFormat
  * timestampNTZFormat
  * pretty
  * timeZone
  * writeNonAsciiCharactersAsCodePoint
  * encoding/charset- probably not supported here
  * spark.sql.jsonGenerator.writeNullIfWithDefaultValue - note sure this one is supported
  * spark.sql.legacy.timeParserPolicy

Do we know what are the input types that they want to support? At the top level Spark supports Struct, and Array (Although most of the code looks like it could support map as well. Not 100% sure what is happening with that we should test it.

What are the required child types? Do they include CalendarIntervalType or any interval type? UserDefinedTypes? Maps that don't have a string as the key?

It mostly comes down to casting things to strings. Doing some escaping if needed and other string manipulation. Not sure how fast it will be with all of the variable length string manipulation that would need to happen, but it should be doable.

**Comment by nvliyuan** [comment]
We can hold on to this feature request for a few days since customers have other higher priorities todo.
CC @viadea
