### ISSUE TITLE
[DOC] Add documentation for running the RAPIDS Accelerator with Spark on Ray

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids#9101]
Relates to #8062.  The Spark resource configs used for most other setups does not work with Spark on Ray.  We should add a getting started document for those trying to run Spark on Ray with the RAPIDS Accelerator.

**Comment by sameerz** [comment]
Let's add information about running on Ray in our FAQ, noting that we do not regularly test on Ray.  The bullet points in https://github.com/NVIDIA/spark-rapids/discussions/8062#discussioncomment-6803746 can be added to the doc: 


- changed the gpuGpusResources.sh script to use \"GPU\" instead of \"gpu\"
- changed the spark.executor.resource.gpu.* configs to corresponding spark.executor.resource.GPU.* configs
- changed spark.task.resource.gpu.amount to spark.task.resource.GPU.amount

**Comment by nvliyuan** [comment]
since #9181  merged, close this issue
