### ISSUE TITLE
[BUG] mvn resolve dependencies failed missing rapids-4-spark-sql-plugin-api_2.12 of 311 shim

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids#9214]
**Describe the bug**
related to https://github.com/NVIDIA/spark-rapids/pull/9148

mvn get or some other dependency commands would fail missing `com.nvidia:rapids-4-spark-sql-plugin-api_2.12:jar:spark311:23.10.0-SNAPSHOT` while try resolve plugin artifact dependencies.

```
00:41:51  [INFO] ------------------------------------------------------------------------
00:41:51  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project rapids-4-spark-parent: Couldn't download artifact: Missing:
00:41:51  [ERROR] ----------
00:41:51  [ERROR] 1) com.nvidia:rapids-4-spark-sql-plugin-api_2.12:jar:spark311:23.10.0-SNAPSHOT
00:41:51  [ERROR] 
00:41:51  [ERROR] Try downloading the file manually from the project website.
00:41:51  [ERROR] 
00:41:51  [ERROR] Then, install it using the command:
00:41:51  [ERROR] mvn install:install-file -DgroupId=com.nvidia -DartifactId=rapids-4-spark-sql-plugin-api_2.12 -Dversion=23.10.0-SNAPSHOT -Dclassifier=spark311 -Dpackaging=jar -Dfile=/path/to/file
00:41:51  [ERROR] 
00:41:51  [ERROR] Alternatively, if you host your own repository you can deploy the file there:
00:41:51  [ERROR] mvn deploy:deploy-file -DgroupId=com.nvidia -DartifactId=rapids-4-spark-sql-plugin-api_2.12 -Dversion=23.10.0-SNAPSHOT -Dclassifier=spark311 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
```

**Steps/Code to reproduce bug**
e.g.
```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -B -Dmaven.repo.local=<path>/.m2 -DrepoUrl=https://urm.nvidia.com/artifactory/sw-spark-maven -Ddest=<path>/jars -DgroupId=com.nvidia -DartifactId=rapids-4-spark_2.12 -Dversion=23.10.0-SNAPSHOT
```
or
```
mvn -U -B -s jenkins/settings.xml -P mirror-apache-to-urm -Dmaven.repo.local=<path>/.m2/repository dependency:go-offline dependency:resolve-plugins -Dcuda.version=cuda11
```

**Expected behavior**
it should pass the mvn get

**Comment by pxLi** [comment]
all other shims API artifacts are available on maven repo, but 311

also cc @gerashegalov to help take a look, thanks

**Comment by gerashegalov** [comment]
The nightly pipeline resumed deploying all necessary [artifacts](https://github.com/NVIDIA/spark-rapids/blob/7e1e9d385783069791021ead1035c671a2ef1921/jenkins/spark-nightly-build.sh#L158-L162) after fixing #9213 

I verified manually that both commands work on an empty local m2 repo.

Moreover `mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get -DartifactId=rapids-4-spark_2.12 ` would have worked even prior to fixing #9213 had it been executed outside the project directory, because it has no [dependency on anything com.nvidia other than a parent pom referencei](https://urm.nvidia.com/artifactory/sw-spark-maven/com/nvidia/rapids-4-spark_2.12/23.10.0-SNAPSHOT/rapids-4-spark_2.12-23.10.0-20230912.133010-30.pom)
