### ISSUE TITLE
[FEA] Support stack function

### ISSUE THREAD

**Issue by viadea** [NVIDIA/spark-rapids#9218]
I wish we can support stack function.

eg.
```
spark-sql> select stack(1,c_customer_id,c_customer_sk) from customer limit 10;

  !Exec <GenerateExec> cannot run on GPU because not all expressions can be replaced
    ! <Stack> stack(1, c_customer_id#25, c_customer_sk#24) cannot run on GPU because GPU does not currently support the operator class org.apache.spark.sql.catalyst.expressions.Stack
```

**Comment by revans2** [comment]
We could try and be fancy and use interleave columns https://github.com/rapidsai/cudf/blob/1911d33231ac9caeaf5310173bf6a47ffca35fe8/cpp/include/cudf/reshape.hpp#L53 along with tile right below it https://github.com/rapidsai/cudf/blob/1911d33231ac9caeaf5310173bf6a47ffca35fe8/cpp/include/cudf/reshape.hpp#L75, but I think we can be much more efficient. 

Stack is a generator function, but there is no guaranteed output order for GenerateExec, so we can probably implement this in terms of GpuExpandExec. The output of GenerateExec is `requiredChildOutput ++ generatorOutput` `requiredChildOutput` are the ride along columns that are going to possibly be replicated. So we take `n`, the first argument to stack that has to be static and then interleave the expressions to produce an input to GpuExpandExec.

For example lets say we have the example up above but expand it to have another columns

```
select stack(1, c_customer_id, c_customer_sk) from customer, some_other_column limit 10;
```

`some_other_column` would be in `requiredChildOutput` of the `GenerateExec`. So we can then rewrite it to be an `ExpandExec` where `projections` would be `[[some_other_column, c_customer_id as col1], [some_other_column, c_customer_sk as col1]]`.  The main reason to do this is because `GpuExpandExec` is already highly optimized so no need to reinvent the wheel.
