### ISSUE TITLE
[QST] Benchmark performance questions

### ISSUE THREAD

**Issue by rohitreddy1698** [NVIDIA/spark-rapids#9278]
**What is your question?**
I am running spark in standalone mode , with 3 nodes , 1 master and 2 workers. 
I am starting pyspark with the following command :
`spark-3.2.3-bin-hadoop3.2/bin/pyspark -v --master spark://mr3-0509-0307-38-jea.mr3.simcloud.apple.com:7077 \
  --conf spark.ui.reverseProxyUrl=http://localhost:4040 \
  --conf spark.driver.port=20002 \
  --conf spark.blockManager.port=30001 \
  --conf spark.executor.port=0
`

And using the following configs :
```
spark.driver.memory 10g
spark.driver.cores 5
spark.driver.memoryOverhead 2g
spark.dynamicAllocation.enabled false
spark.executor.memory 10g
spark.executor.cores 10
spark.executor.instances 2
spark.executor.resource.gpu.amount 1
spark.rapids.sql.concurrentGpuTasks 5
spark.executor.resource.gpu.discoveryScript /root/getGpusResources.sh
spark.sql.files.maxPartitionBytes 1g
spark.rapids.memory.pinnedPool.size 20g
spark.locality.wait 0
spark.sql.adaptive.enabled true
spark.eventLog.enabled true
spark.eventLog.dir /root/eventLogs
spark.history.fs.cleaner.enabled true
spark.history.fs.cleaner.interval 48h
spark.history.fs.cleaner.maxAge 30d
spark.history.provider org.apache.spark.deploy.history.FsHistoryProvider
spark.history.ui.maxApplications 10
spark.history.ui.port 18080
spark.history.fs.logDirectory /root/eventLogs

spark.task.resource.gpu.amount 0.10
spark.rapids.sql.enabled true
spark.plugins com.nvidia.spark.SQLPlugin
spark.rapids.sql.variableFloatAgg.enabled true

spark.driver.extraClassPath /root/rapids-jars/rapids-4-spark_2.12-23.02.0.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/hadoop-aws-3.3.4.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/aws-java-sdk-bundle-1.11.999.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/s3a-extension-0.0.1.jar
spark.executor.extraClassPath /root/rapids-jars/rapids-4-spark_2.12-23.02.0.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/hadoop-aws-3.3.4.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/aws-java-sdk-bundle-1.11.999.jar:/root/spark-3.2.3-bin-hadoop3.2/jars/s3a-extension-0.0.1.jar
spark.jars /root/rapids-jars/rapids-4-spark_2.12-23.02.0.jar,/root/spark-3.2.3-bin-hadoop3.2/jars/hadoop-aws-3.3.4.jar,/root/spark-3.2.3-bin-hadoop3.2/jars/aws-java-sdk-bundle-1.11.999.jar,/root/spark-3.2.3-bin-hadoop3.2/jars/s3a-extension-0.0.1.jar

spark.hadoop.fs.conductor.impl com.apple.aiml.hadoop.fs.conductor.ConductorS3AImpl
spark.hadoop.fs.conductor.endpoint https://conductor-qa.data.apple.com
spark.hadoop.fs.conductor.path.style.access true

spark.shuffle.service.enabled true
spark.local.dir /root/spark-3.2.3-bin-hadoop3.2/work_dir
spark.sql.shuffle.partitions 200
spark.sql.sources.bucketing.enabled TRUE

```

I have my data in s3 compatible storage , when I am trying out the examples here : https://github.com/NVIDIA/spark-rapids-examples/blob/branch-23.08/examples/SQL%2BDF-Examples/micro-benchmarks/notebooks/micro-benchmarks-gpu.ipynb

```
>>> runMicroBenchmark(spark,"Windowing without skew",query,2)
+--------------+-------------+                                                  
|ss_customer_sk|    avg_price|
+--------------+-------------+
|       3693411|56.9074157833|
|        470187|56.1645528028|
|       1321810|55.5717568105|
|       3309242|55.4511777857|
|       5905594|55.2988594754|
+--------------+-------------+
only showing top 5 rows

Retry times : 1, Windowing without skew microbenchmark takes 538.82 seconds
+--------------+-------------+                                                  
|ss_customer_sk|    avg_price|
+--------------+-------------+
|       3693411|56.9254591667|
|        470187|56.0018028028|
|       1321810|55.5717568105|
|       3309242|55.4511777857|
|       5905594|55.2988594754|
+--------------+-------------+
only showing top 5 rows

Retry times : 2, Windowing without skew microbenchmark takes 515.52 seconds
Windowing without skew microbenchmark takes average 527 seconds after 2 retries
>>> 

```

I am checking the GPU usage via nvidia-smi and I see the GPU is being used , but I am getting the same performance for the query when I run it with RAPIDS disabled.

Can you please help me understand why am I unable to see the performance difference.

Thank you

**Comment by rohitreddy1698** [comment]
I am facing the same issue for Windowing with skew and also runMicroBenchmark(spark,"NDS Q14a subquery",query,2) , Intersection Query , but able to see performance gains in Expand&HashAggregate microbenchmark and Crossjoin microbenchmark

**Comment by revans2** [comment]
What CPU hardware are you comparing the GPU run against? What scale factor is the tpcds data? What GPUs are you using? A parallelism of 5 looks kind of high.

For me I ran the skewed window test with an a6000 on default settings Scale Factor 200 with Spark 3.3.0 local mode and an 80 GiB Heap (more for the CPU than anything).  I got

14747, 11016, 10629, 10465, and 10352 in ms for the runs. The average time is 11.4 seconds. The median time is 10.6 seconds

For the CPU it took much longer because it is on an old 12 thread 6 core intel CPU. I didn't do all 5 runs, because it took too long.

294341 and 288585 ms.

If I take the better of the two then I see speedup somewhere between 19.5x and 27.9x

I tried to do some tuning, but it didn't really help all that much because the query on the GPU tends to be very I/O bound, even in local mode with essentially all of the input data in the page cache. The parquet decoding was somewhat expensive, because it didn't fully utilize the GPU. It is more that there just wasn't a lot of data (6.3 GiB spread across 222 tasks) so the GPU could not get a lot of parallelism for each operation. The shuffle is where most of the time is being taken, at least for my setup.  Could possibly see some differences if we can reproduce the problem with similar hardware to what you are using.

**Comment by sameerz** [comment]
Hi @rohitreddy1698 let us know if the above answers helps.  Please reopen if you have further questions, we are also happy to set up a meeting to discuss if you like.

**Comment by rohitreddy1698** [comment]
Hello , I am sorry for the delayed response my Gmail storage got full and did not get the mail notification for the replies.
Thank you for your response.

I figured out the issue , I was using a containerised environment where the range of the usable ports was very limited and the multi threaded approach was not working fine.

I was able to get this working. Thank you

Rohit Mothe
