### ISSUE TITLE
tpc-ds qeury82 shuffle data size is abnormal [QST]

### ISSUE THREAD

**Issue by chenrui17** [NVIDIA/spark-rapids#930]
when I test tpc-ds query-82, cpu shuffle write data size is 105GB+, while shuffle read data size is 3GB+,
GPU rapids shuffle write and read data size is both 80GB+ , so I compared tow dag  is below :
cpu:                                                                                  
![image](https://user-images.githubusercontent.com/33319780/95747904-c3ee4980-0ccb-11eb-9992-efbbf75edab2.png)
gpu:
![image](https://user-images.githubusercontent.com/33319780/95748092-129be380-0ccc-11eb-86c3-332b47057c79.png)

I have 2 questions ,
1. in general , shuffle write data size is equal shuffle write data size , but query-82 shuffle read data is less than write ,why ? what it happend ?
2. can rapids add this feature to reduce shuffle read data size to improve performance ?

**Comment by revans2** [comment]
I would have to look at what in the query is reading the shuffle data.  Spark has some operators that stop processing early if they can tell that they don't need to process any more data.  In some cases they can even avoid running entire tasks.  We recently hit one of theses issues with #900. I don't think this is the same issue because query 82 has an order by before the limit, which usually will translate into a `TakeOrderedAndProject` instead of a regular `Limit`, but I would have to look into the details of the plan to be sure.

**Comment by jlowe** [comment]
Closing this old issue.  Please reopen if still relevant.
